### ISSUE TITLE
从互联网更新书籍信息时图片设置错误

### ISSUE THREAD

**Issue by LGinC** [talebook/talebook#103]
```python
Exception:
Traceback (most recent call last):
  File "/var/www/calibre-webserver/webserver/handlers/base.py", line 54, in do
    try: rsp = func(self, *args, **kwargs)
  File "/var/www/calibre-webserver/webserver/handlers/base.py", line 75, in do
    return func(self, *args, **kwargs)
  File "/var/www/calibre-webserver/webserver/handlers/book.py", line 302, in post
    self.db.set_metadata(book_id, mi)
  File "/usr/lib/calibre/calibre/db/legacy.py", line 464, in set_metadata
    self.new_api.set_metadata(book_id, mi, ignore_errors=ignore_errors, set_title=set_title, set_authors=set_authors, force_changes=force_changes)
  File "/usr/lib/calibre/calibre/db/cache.py", line 61, in call_func_with_lock
    return func(*args, **kwargs)
  File "/usr/lib/calibre/calibre/db/cache.py", line 1279, in set_metadata
    self._set_cover({book_id: cdata})
  File "/usr/lib/calibre/calibre/db/cache.py", line 1205, in set_cover
    self.backend.set_cover(book_id, path, data)
  File "/usr/lib/calibre/calibre/db/backend.py", line 1401, in set_cover
    save_cover_data_to(data, path)
  File "/usr/lib/calibre/calibre/utils/img.py", line 197, in save_cover_data_to
    f.write(image_to_data(img, compression_quality, fmt) if changed else data)
  File "/usr/lib/calibre/calibre/utils/img.py", line 137, in image_to_data
    raise ValueError('Failed to export image as ' + fmt + ' with error: ' + w.errorString())
ValueError: Failed to export image as JPEG with error: Unknown error
```

目前发现有这3本书的图片报错
https://img2.doubanio.com/view/subject/l/public/s3897231.jpg
https://img2.doubanio.com/view/subject/l/public/s2741832.jpg
https://img2.doubanio.com/view/subject/l/public/s3329042.jpg

**Comment by LGinC** [comment]
[img.py](https://github.com/kovidgoyal/calibre/blob/85c25916a3ad1d2051ce3cbfd653b15247d6db99/src/calibre/utils/img.py#L146)好像有更新了

可以把calibre升级到[5.x](https://github.com/kovidgoyal/calibre/releases)吗

**Comment by talebook** [comment]
> [img.py](https://github.com/kovidgoyal/calibre/blob/85c25916a3ad1d2051ce3cbfd653b15247d6db99/src/calibre/utils/img.py#L146)好像有更新了
> 
> 可以把calibre升级到[5.x](https://github.com/kovidgoyal/calibre/releases)吗

不能。calibre的master已经是python3，但我们还是python2。 支持python3的分支还在开发中。

**Comment by LGinC** [comment]
最新版已修复此问题
