### ISSUE TITLE
Dead lock for sqlite3

### ISSUE THREAD

**Issue by syhily** [talebook/talebook#120]
It often occurs when I review the book details page. The sample site: https://read.yufan.run

```text
Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/base.py", line 1802, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: database is locked

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/www/talebook/webserver/handlers/base.py", line 54, in do
    try: rsp = func(self, *args, **kwargs)
  File "/var/www/talebook/webserver/handlers/book.py", line 176, in get
    self.user_history('visit_history', book)
  File "/var/www/talebook/webserver/handlers/base.py", line 245, in user_history
    user.save()
  File "/usr/local/lib/python3.9/dist-packages/social_sqlalchemy/storage.py", line 82, in save
    self._save_instance(self)
  File "/usr/local/lib/python3.9/dist-packages/social_sqlalchemy/storage.py", line 64, in _save_instance
    cls._session().commit()
  File "", line 2, in commit
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/session.py", line 1431, in commit
    self._transaction.commit(_to_root=self.future)
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/session.py", line 829, in commit
    self._prepare_impl()
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/session.py", line 808, in _prepare_impl
    self.session.flush()
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/session.py", line 3363, in flush
    self._flush(objects)
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/session.py", line 3503, in _flush
    transaction.rollback(_capture_exception=True)
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/session.py", line 3463, in _flush
    flush_context.execute()
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/unitofwork.py", line 456, in execute
    rec.execute(self)
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/unitofwork.py", line 630, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/persistence.py", line 236, in save_obj
    _emit_update_statements(
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/persistence.py", line 1000, in _emit_update_statements
    c = connection._execute_20(
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/base.py", line 1614, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/sql/elements.py", line 325, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/base.py", line 1481, in _execute_clauseelement
    ret = self._execute_context(
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/base.py", line 1845, in _execute_context
    self._handle_dbapi_exception(
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/base.py", line 2026, in _handle_dbapi_exception
    util.raise_(
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/base.py", line 1802, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database is locked
[SQL: UPDATE readers SET extra=? WHERE readers.id = ?]
[parameters: ('{"kindle_email": "", "login_ip": "172.68.133.97", "download_history": [{"id": 20172, "title": "\\u59b9\\u59b9\\u7684\\u575f\\u5893", "timestamp": 164 ... (31606 characters truncated) ... 4e4b\\u4ed9\\u754c\\u7bc7", "timestamp": 1643211695}, {"id": 27642, "title": "\\u4e5d\\u5dde\\u00b7\\u620f\\u4e2d\\u4eba", "timestamp": 1643211670}]}', 9058)]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
```

**Comment by syhily** [comment]
The reason for the database lock is that the [extra](https://github.com/talebook/talebook/blob/181e2d3ad420c06e12af8ce3f8045017e5bfc91e/webserver/models.py#L93) column is too big to store. I think we can just move the read history to a new table.

**Comment by talebook** [comment]
I'm gonna set a limit of the max items of history in extra column, because currently the history is not important and saving the recent N history maybe enough.

**Comment by syhily** [comment]
Thanks for your response. I see, but it would be better to set the download & read history to a separate table. We can have an unlimited history for recording what we have seen. The performance is also better than before.

I think that the metadata in user extra is also needed to change to the table columns.

**Comment by syhily** [comment]
I have dropped the `user_history` method on my running [talebook instance](https://read.yufan.run), everything works fine now. So I think we can take more time to get this better designed.

**Comment by syhily** [comment]
I still meet this error after updating to the latest docker release.

**Comment by talebook** [comment]
it works fine on my server with hundreds of get request. Please try to set SQLITE_MAX_LENGTH = 30*1024 at models.py  line 86, it may trigger the shrink progress and clean the bad data.

**Comment by syhily** [comment]
Everything seems OK now after trying your suggestion. I'll close this issue now.
