### ISSUE TITLE
Vuejs 报错

### ISSUE THREAD

**Issue by imoasislee** [talebook/talebook#121]
Uncaught TypeError: Cannot set properties of undefined (setting 'transform')
    at mr (vue.runtime.esm.js:7158:34)
    at Array.br (vue.runtime.esm.js:7219:15)
    at w (vue.runtime.esm.js:6063:23)
    at p (vue.runtime.esm.js:5950:29)
    at y (vue.runtime.esm.js:6047:19)
    at p (vue.runtime.esm.js:5948:24)
    at o.__patch__ (vue.runtime.esm.js:6471:17)
    at o.Ti.t._update (vue.runtime.esm.js:3939:19)
    at o.s (vue.runtime.esm.js:4060:10)
    at es.get (vue.runtime.esm.js:4473:25)

vue.runtime.esm.js:1888 TypeError: Cannot read properties of undefined (reading '_transitionClasses')
    at Array.Wn (vue.runtime.esm.js:6809:28)
    at A (vue.runtime.esm.js:6308:73)
    at k (vue.runtime.esm.js:6187:20)
    at A (vue.runtime.esm.js:6313:44)
    at k (vue.runtime.esm.js:6187:20)
    at A (vue.runtime.esm.js:6313:44)
    at o.__patch__ (vue.runtime.esm.js:6476:20)
    at o.Ti.t._update (vue.runtime.esm.js:3942:19)
    at o.s (vue.runtime.esm.js:4060:10)
    at es.get (vue.runtime.esm.js:4473:25)

**Comment by talebook** [comment]
版本号是多少？哪个操作触发该保存？

**Comment by imoasislee** [comment]
最新版本 应该是3.1.30
访问主页空白，控制台显示上述错误
无论是docker还是手动部署，直接访问ip:port不会有该问题，但是使用nginx后就会报错（手动部署的nginx也是按照文档来写的）
请问如果使用docker部署，nginx的配置是否有什么需要注意的呢？
```
server{
        server_name mydomain;
        listen 80;
        listen 443 ssl http2;
        include ssl.conf;
        client_max_body_size 0;
        location / {
                proxy_pass http://127.0.0.1:8175/;
                proxy_set_header Host mydomain;
                proxy_set_header X-Scheme $scheme;
                }
}
```

**Comment by talebook** [comment]
proxy_set_header Host $http_host;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_pass_header X-Scheme

请这样配置

**Comment by imoasislee** [comment]
依然报错，另外补充一下，在macOS12.1的Safari上可以正常打开，但报错`minimal-ui not recognized and ignored` 
![](https://images.imoasislee.com/202201291105352.png)
在iOS15.3上也可以打开；
而在macOS12.1的Chrome（97.0.4692.99）上报上述错误；iPadOS15.3也无法打开。
由于没有学习过前端知识，我只能尝试将vuejs在本地部署，使用同版本Chrome打开后无上述报错。

**Comment by talebook** [comment]
该问题无法复现和排查。暂时关闭掉。
