### ISSUE TITLE
没有填写书籍ISBN的时候从互联网更新信息出错

### ISSUE THREAD

**Issue by ntzw** [talebook/talebook#122]
```
Exception:
Traceback (most recent call last):
  File "/var/www/talebook/webserver/handlers/base.py", line 47, in do
    rsp = func(self, *args, **kwargs)
  File "/var/www/talebook/webserver/handlers/base.py", line 73, in do
    return func(self, *args, **kwargs)
  File "/var/www/talebook/webserver/handlers/book.py", line 275, in get
    books = self.plugin_search_books(mi)
  File "/var/www/talebook/webserver/handlers/book.py", line 232, in plugin_search_books
    book = api.get_book_by_isbn(mi.isbn)
  File "/var/www/talebook/webserver/plugins/meta/douban.py", line 58, in get_book_by_isbn
    rsp = requests.get(url, headers=CHROME_HEADERS, params=args).json()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

有设置豆瓣API，有ISBN编号的书籍，获取信息不会报错

**Comment by talebook** [comment]
3.1.35版本应该是正常的。之前的版本没有很好地处理边界异常的情况，3.1.35里优化了。

**Comment by ntzw** [comment]
> 3.1.35版本应该是正常的。之前的版本没有很好地处理边界异常的情况，3.1.35里优化了。
