### ISSUE TITLE
邮件服务在启用2步认证后出现异常

### ISSUE THREAD

**Issue by xxxsen** [talebook/talebook#127]
版本: v3.2.1
测试了gmail/qq 在启用2步认证后, 采用授权码进行登录, 都无法成功发信。

gmail 直接无反应, 在等了60s后弹出504的错误(网络是通的, tcpdump抓包可以看到链接建立)。

```text
[E 220209 13:41:41 user:167] Traceback (most recent call last):
      File "/var/www/talebook/webserver/handlers/user.py", line 154, in post
        self.mail(
      File "/var/www/talebook/webserver/handlers/base.py", line 502, in mail
        sendmail(
      File "/usr/lib/calibre/calibre/utils/smtp.py", line 179, in sendmail
        s = cls(**kwargs)
      File "/usr/lib/calibre/polyglot/smtplib.py", line 49, in __init__
        super().__init__(*a, **kw)
      File "/usr/lib/python3.9/smtplib.py", line 1034, in __init__
        SMTP.__init__(self, host, port, local_hostname, timeout,
      File "/usr/lib/python3.9/smtplib.py", line 253, in __init__
        (code, msg) = self.connect(host, port)
      File "/usr/lib/python3.9/smtplib.py", line 339, in connect
        self.sock = self._get_socket(host, port, self.timeout)
      File "/usr/lib/python3.9/smtplib.py", line 1041, in _get_socket
        new_socket = self.context.wrap_socket(new_socket,
      File "/usr/lib/python3.9/ssl.py", line 500, in wrap_socket
        return self.sslsocket_class._create(
      File "/usr/lib/python3.9/ssl.py", line 1040, in _create
        self.do_handshake()
      File "/usr/lib/python3.9/ssl.py", line 1309, in do_handshake
        self._sslobj.do_handshake()
    ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:1123)
```

QQ邮箱提示无效输入
![image](https://user-images.githubusercontent.com/3880276/153215234-9b60b6c2-3348-4548-a061-737e702f8f6c.png)
```text
[E 220209 13:53:53 user:167] Traceback (most recent call last):
      File "/var/www/talebook/webserver/handlers/user.py", line 154, in post
        self.mail(
      File "/var/www/talebook/webserver/handlers/base.py", line 502, in mail
        sendmail(
      File "/usr/lib/calibre/calibre/utils/smtp.py", line 191, in sendmail
        s.sendmail(from_, to, msg)
      File "/usr/lib/python3.9/smtplib.py", line 871, in sendmail
        raise SMTPSenderRefused(code, resp, from_addr)
    smtplib.SMTPSenderRefused: (502, b'Invalid input from 1.2.3.4 to newxmesmtplogicsvrsza9.qq.com.', '111111')
```

**Comment by xxxsen** [comment]
> 我用的是QQ邮箱的授权码，是正常的。你可以检查下：1，服务器的25端口是否可正常使用；2，使用其他软件测试下授权码是否正常。

知道原因了，qq邮箱的话，要把后缀的`@qq.com` 给带上, 不然就会出现哪个`invalid input`的错误。= =、、
