### ISSUE TITLE
管理后台--导入图书界面报错

### ISSUE THREAD

**Issue by gzsxy** [talebook/talebook#149]
Exception:<br><pre style="white-space:pre-wrap;word-break:keep-all">Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/base.py", line 1802, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such table: scanfiles

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/www/talebook/webserver/handlers/base.py", line 50, in do
    rsp = func(self, *args, **kwargs)
  File "/var/www/talebook/webserver/handlers/base.py", line 77, in do
    return func(self, *args, **kwargs)
  File "/var/www/talebook/webserver/handlers/scan.py", line 274, in get
    total = query.count()
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/query.py", line 3145, in count
    return self._from_self(col).enable_eagerloads(False).scalar()
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/query.py", line 2879, in scalar
    ret = self.one()
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/query.py", line 2856, in one
    return self._iter().one()
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/query.py", line 2894, in _iter
    result = self.session.execute(
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/session.py", line 1692, in execute
    result = conn._execute_20(statement, params or {}, execution_options)
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/base.py", line 1614, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/sql/elements.py", line 325, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/base.py", line 1481, in _execute_clauseelement
    ret = self._execute_context(
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/base.py", line 1845, in _execute_context
    self._handle_dbapi_exception(
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/base.py", line 2026, in _handle_dbapi_exception
    util.raise_(
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/base.py", line 1802, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: scanfiles
[SQL: SELECT count(*) AS count_1 
FROM (SELECT scanfiles.id AS scanfiles_id, scanfiles.scan_id AS scanfiles_scan_id, scanfiles.import_id AS scanfiles_import_id, scanfiles.name AS scanfiles_name, scanfiles.path AS scanfiles_path, scanfiles.hash AS scanfiles_hash, scanfiles.status AS scanfiles_status, scanfiles.title AS scanfiles_title, scanfiles.author AS scanfiles_author, scanfiles.publisher AS scanfiles_publisher, scanfiles.tags AS scanfiles_tags, scanfiles.create_time AS scanfiles_create_time, scanfiles.update_time AS scanfiles_update_time, scanfiles.book_id AS scanfiles_book_id, scanfiles.data AS scanfiles_data 
FROM scanfiles ORDER BY scanfiles.create_time DESC) AS anon_1]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
</pre>
![图片](https://user-images.githubusercontent.com/23026142/162602576-ea3cdddf-c0db-4820-9f51-db947e732715.png)

Exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/base.py", line 1802, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such table: scanfiles

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/www/talebook/webserver/handlers/base.py", line 50, in do
    rsp = func(self, *args, **kwargs)
  File "/var/www/talebook/webserver/handlers/base.py", line 77, in do
    return func(self, *args, **kwargs)
  File "/var/www/talebook/webserver/handlers/scan.py", line 274, in get
    total = query.count()
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/query.py", line 3145, in count
    return self._from_self(col).enable_eagerloads(False).scalar()
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/query.py", line 2879, in scalar
    ret = self.one()
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/query.py", line 2856, in one
    return self._iter().one()
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/query.py", line 2894, in _iter
    result = self.session.execute(
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/session.py", line 1692, in execute
    result = conn._execute_20(statement, params or {}, execution_options)
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/base.py", line 1614, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/sql/elements.py", line 325, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/base.py", line 1481, in _execute_clauseelement
    ret = self._execute_context(
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/base.py", line 1845, in _execute_context
    self._handle_dbapi_exception(
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/base.py", line 2026, in _handle_dbapi_exception
    util.raise_(
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/base.py", line 1802, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: scanfiles
[SQL: SELECT count(*) AS count_1 
FROM (SELECT scanfiles.id AS scanfiles_id, scanfiles.scan_id AS scanfiles_scan_id, scanfiles.import_id AS scanfiles_import_id, scanfiles.name AS scanfiles_name, scanfiles.path AS scanfiles_path, scanfiles.hash AS scanfiles_hash, scanfiles.status AS scanfiles_status, scanfiles.title AS scanfiles_title, scanfiles.author AS scanfiles_author, scanfiles.publisher AS scanfiles_publisher, scanfiles.tags AS scanfiles_tags, scanfiles.create_time AS scanfiles_create_time, scanfiles.update_time AS scanfiles_update_time, scanfiles.book_id AS scanfiles_book_id, scanfiles.data AS scanfiles_data 
FROM scanfiles ORDER BY scanfiles.create_time DESC) AS anon_1]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
![图片](https://user-images.githubusercontent.com/23026142/162602586-7679cdab-99a9-4acd-98ee-3f7ec637327b.png)

补充一下，运行版本为群晖dock 3.5.4

**Comment by talebook** [comment]
这是旧版本数据库没有升级导致的，目前功能还在beta中，后续会做自动升级。

**Comment by syhily** [comment]
@talebook I think we can add syncdb in `start.sh`

**Comment by talebook** [comment]
> @talebook I think we can add syncdb in [start.sh](https://github.com/talebook/talebook/blob/040c06857f48fd2fa434302b344ddec636098d73/docker/start.sh#L27), no need to use prebuilt database file. This will also add other database support out of box.
> 
> ```
> /var/www/talebook/server.py --syncdb
> /var/www/talebook/server.py --update-config
> ```

初步看，sqlalchemy这个库的syncdb功能能create table，但并不会做migration。如果表格增加字段，就凉凉。
导入功能目前还在开发，库表设计还有些在斟酌中； 另外我也想研究下怎么做平滑升级，所以暂时不打算增加syncdb到start.sh里。

**Comment by syhily** [comment]
> > @talebook I think we can add syncdb in [start.sh](https://github.com/talebook/talebook/blob/040c06857f48fd2fa434302b344ddec636098d73/docker/start.sh#L27), no need to use prebuilt database file. This will also add other database support out of box.
> > ```
> > /var/www/talebook/server.py --syncdb
> > /var/www/talebook/server.py --update-config
> > ```
> 
> 初步看，sqlalchemy这个库的syncdb功能能create table，但并不会做migration。如果表格增加字段，就凉凉。 导入功能目前还在开发，库表设计还有些在斟酌中； 另外我也想研究下怎么做平滑升级，所以暂时不打算增加syncdb到start.sh里。

Tks for your clarification.

**Comment by gzsxy** [comment]
> 

好的，辛苦作者

**Comment by adogshz** [comment]
保存下列sql，找个数据库管理工具，执行之，记得执行前，备份你的库。

`DROP TABLE IF EXISTS "main"."scanfiles";
CREATE TABLE scanfiles (
	id INTEGER NOT NULL, 
	scan_id INTEGER, 
	import_id INTEGER, 
	name VARCHAR(512), 
	path VARCHAR(1024), 
	hash VARCHAR(512), 
	status VARCHAR(24), 
	title VARCHAR(100), 
	author VARCHAR(100), 
	publisher VARCHAR(100), 
	tags VARCHAR(100), 
	create_time DATETIME, 
	update_time DATETIME, 
	book_id INTEGER, 
	data TEXT, 
	PRIMARY KEY (id), 
	UNIQUE (hash)
);`

**Comment by talebook** [comment]
`v3.5.6`版本已经补上了自动升级书库的功能

**Comment by gzsxy** [comment]
> `v3.5.6`版本已经补上了自动升级书库的功能

感谢大佬
