### ISSUE TITLE
首次启动报数据库锁定错误(database is locked)

### ISSUE THREAD

**Issue by xiaofeng-han** [talebook/talebook#155]
[I 220413 18:39:39 main:129] Init library with [/data/books/library]
[I 220413 18:39:39 main:130] Init AuthDB  with [sqlite:////data/books/calibre-webserver.db]
[I 220413 18:39:39 main:131] Init Static  with [/var/www/talebook/webserver/resources]
[I 220413 18:39:39 main:132] Init HTML    with [/var/www/talebook/webserver/../app/dist]
[I 220413 18:39:39 main:133] Init Nuxtjs  with [/var/www/talebook/webserver/../app/.env]
Traceback (most recent call last):
  File "/var/www/talebook/server.py", line 13, in <module>
    sys.exit(webserver.main.main())
  File "/var/www/talebook/webserver/main.py", line 215, in main
    app = make_app()
  File "/var/www/talebook/webserver/main.py", line 144, in make_app
    book_db = LibraryDatabase(os.path.expanduser(options.with_library))
  File "/usr/lib/calibre/calibre/db/legacy.py", line 188, in __init__
    backend = self.backend = create_backend(library_path, default_prefs=default_prefs,
  File "/usr/lib/calibre/calibre/db/legacy.py", line 45, in create_backend
    return DB(library_path, default_prefs=default_prefs,
  File "/usr/lib/calibre/calibre/db/backend.py", line 453, in __init__
    SchemaUpgrade(self, self.library_path, self.field_metadata)
  File "/usr/lib/calibre/calibre/db/schema_upgrades.py", line 19, in __init__
    db.execute('BEGIN EXCLUSIVE TRANSACTION')
  File "/usr/lib/calibre/calibre/db/backend.py", line 920, in execute
    return self.conn.cursor().execute(sql, bindings)
apsw.BusyError: BusyError: database is locked

**Comment by xiaofeng-han** [comment]
看来是我把一个smbshare的folder指定为/data的问题，应该是文件权限不对
