### ISSUE TITLE
iPhone ios14以上机型在线无法阅读epub格式

### ISSUE THREAD

**Issue by laverdelee** [talebook/talebook#173]
测试iPhone ios14以上，不同手机，ipad，不同浏览器，均无法在线阅读epub格式。电脑浏览器支持在线阅读。

**Comment by vicjianling** [comment]
这个我遇到了

**Comment by laverdelee** [comment]
查看日志发现手机在线阅读时，加载不出来，[I 220507 13:35:58 web:2239] 200 GET /read/27 (172.17.0.1) 989.97ms

**Comment by laverdelee** [comment]
查看日志，显示error如下：
[E 220507 14:19:20 web:1789] Uncaught exception GET /read/11 (172.17.0.1)
    HTTPServerRequest(protocol='http', host='IP:8080', method='GET', uri='/read/11', version='HTTP/1.0', remote_ip='172.17.0.1')
    Traceback (most recent call last):
      File "/usr/local/lib/python3.9/dist-packages/tornado/web.py", line 1702, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/var/www/talebook/webserver/handlers/book.py", line 489, in get
        self.count_increase(book_id, count_download=1)
      File "/var/www/talebook/webserver/handlers/base.py", line 432, in count_increase
        item.save()
      File "/usr/local/lib/python3.9/dist-packages/social_sqlalchemy/storage.py", line 82, in save
        self._save_instance(self)
      File "/usr/local/lib/python3.9/dist-packages/social_sqlalchemy/storage.py", line 62, in _save_instance
        cls._session().add(instance)
      File "<string>", line 2, in add
      File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/session.py", line 2606, in add
        self._save_or_update_state(state)
      File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/session.py", line 2619, in _save_or_update_state
        self._save_or_update_impl(state)
      File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/session.py", line 3203, in _save_or_update_impl
        self._update_impl(state)
      File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/session.py", line 3186, in _update_impl
        to_attach = self._before_attach(state, obj)
      File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/session.py", line 3280, in _before_attach
        raise sa_exc.InvalidRequestError(
    sqlalchemy.exc.InvalidRequestError: Object '<Item at 0x7ff998ca4f40>' is already attached to session '28' (this is '29')
