### ISSUE TITLE
docker部署始终无法启动

### ISSUE THREAD

**Issue by fantasyjqc** [talebook/talebook#186]
docker模式部署的，docker-compose信息如下：

`  calibre-web:
    image: talebook/calibre-webserver
    container_name: calibre-web
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
    volumes:
      - /mnt/share2/Books:/data/books
    ports:
      - 8383:80
    restart: unless-stopped`

/mnt/share2/Books是一个samba挂载过来的目录，始终无法启动，错误日志如下：

`Traceback (most recent call last):
  File "/var/www/talebook/server.py", line 13, in <module>
    sys.exit(webserver.main.main())
  File "/var/www/talebook/webserver/main.py", line 217, in main
    app = make_app()
  File "/var/www/talebook/webserver/main.py", line 157, in make_app
    book_db = LibraryDatabase(os.path.expanduser(options.with_library))
  File "/usr/lib/calibre/calibre/db/legacy.py", line 188, in __init__
    backend = self.backend = create_backend(library_path, default_prefs=default_prefs,
  File "/usr/lib/calibre/calibre/db/legacy.py", line 45, in create_backend
    return DB(library_path, default_prefs=default_prefs,
  File "/usr/lib/calibre/calibre/db/backend.py", line 453, in __init__
    SchemaUpgrade(self, self.library_path, self.field_metadata)
  File "/usr/lib/calibre/calibre/db/schema_upgrades.py", line 19, in __init__
    db.execute('BEGIN EXCLUSIVE TRANSACTION')
  File "/usr/lib/calibre/calibre/db/backend.py", line 920, in execute
    return self.conn.cursor().execute(sql, bindings)
apsw.BusyError: BusyError: database is locked`

查询过往的issues看到应该是权限问题，说是无法读写/mnt/share2/Books这个目录，但是这应该是不可能的事情，因为docker成功在这个目录下面初始化了数据库文件：

![image](https://user-images.githubusercontent.com/4988150/170774462-ab9fc8bb-c317-48e9-b306-851695721543.png)

不知道问题出在哪里，希望能解决一下。

**Comment by miRemid** [comment]
一样的问题，权限没有问题，但是启动不了

**Comment by wcz0** [comment]
same

**Comment by talebook** [comment]
> same

你遇到的问题也是『database locked』？
这个有可能是PC版calibre没有正常关闭，数据库文件有异常

**Comment by wcz0** [comment]
> 你遇到的问题也是『database locked』？ 这个有可能是PC版calibre没有正常关闭，数据库文件有异常

应该不是, 我的是docker, 一直卡在更新 权限 那, 我用docker-compose 部署, 数据删了也启动不了. 不知道啥原因. 有空再重新测试一遍了

**Comment by wzyqlxp** [comment]
问题解决了吗，我现在也是碰到这个问题，解决不了了

**Comment by roryj11** [comment]
> 问题解决了吗，我现在也是碰到这个问题，解决不了了

启动后进入终端，输入 chmod 777 -R /data  我是这么解决的
