### ISSUE TITLE
最新的3.5.9版本在Nas上用Docker安装后过段时间就会报错，打开站点什么都没有

### ISSUE THREAD

**Issue by NeedforGit** [talebook/talebook#191]
最新的3.5.9版本在Nas上用Docker安装后, 刚开始能正常浏览，但过段时间重新登陆就会报错，打开站点主页，没有登陆选项，之前上传的书也没有了，空空如也，主页弹出的错误如下：

Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/base.py", line 3280, in _wrap_pool_connect
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/pool/base.py", line 310, in connect
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/pool/base.py", line 868, in _checkout
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/pool/base.py", line 476, in checkout
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/pool/base.py", line 256, in _create_connection
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/pool/base.py", line 371, in __init__
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/pool/base.py", line 666, in __connect
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/util/compat.py", line 207, in raise_
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/pool/base.py", line 661, in __connect
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/create.py", line 590, in connect
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/default.py", line 597, in connect
sqlite3.OperationalError: unable to open database file

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/www/talebook/webserver/handlers/base.py", line 51, in do
  File "/var/www/talebook/webserver/handlers/user.py", line 365, in get
  File "/var/www/talebook/webserver/handlers/user.py", line 281, in get_sys_info
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/query.py", line 2888, in scalar
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/query.py", line 2865, in one
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/query.py", line 2903, in _iter
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/session.py", line 1691, in execute
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/session.py", line 1532, in _connection_for_bind
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/session.py", line 747, in _connection_for_bind
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/base.py", line 3234, in connect
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/base.py", line 96, in __init__
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/base.py", line 3313, in raw_connection
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/base.py", line 3283, in _wrap_pool_connect
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/base.py", line 2117, in _handle_dbapi_exception_noconnection
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/util/compat.py", line 207, in raise_
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/base.py", line 3280, in _wrap_pool_connect
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/pool/base.py", line 310, in connect
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/pool/base.py", line 868, in _checkout
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/pool/base.py", line 476, in checkout
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/pool/base.py", line 256, in _create_connection
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/pool/base.py", line 371, in __init__
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/pool/base.py", line 666, in __connect
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/util/compat.py", line 207, in raise_
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/pool/base.py", line 661, in __connect
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/create.py", line 590, in connect
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/default.py", line 597, in connect
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) unable to open database file
(Background on this error at: https://sqlalche.me/e/14/e3q8)

请问怎样解决？感谢！

**Comment by talebook** [comment]
sqlite3.OperationalError: unable to open database file

看起来是文件权限不对

**Comment by NeedforGit** [comment]
感谢回复，我不折腾了，放弃我的垃圾NAS了，换vps上搞，目前装的最新版，没出现这个问题。
