### ISSUE TITLE
页面报错，还请大佬帮忙看看

### ISSUE THREAD

**Issue by Pan06da** [talebook/talebook#246]
Exception:
Traceback (most recent call last):
  File "/var/www/talebook/webserver/handlers/base.py", line 51, in do
    rsp = func(self, *args, **kwargs)
  File "/var/www/talebook/webserver/handlers/base.py", line 89, in do
    return func(self, *args, **kwargs)
  File "/var/www/talebook/webserver/handlers/scan.py", line 363, in post
    total = m.run_import(hashlist)
  File "/var/www/talebook/webserver/handlers/scan.py", line 181, in run_import
    self.do_import(hashlist)
  File "/var/www/talebook/webserver/handlers/scan.py", line 214, in do_import
    row.book_id = self.db.import_book(mi, [fpath])
  File "/usr/lib/calibre/calibre/db/legacy.py", line 362, in import_book
    book_ids, duplicates = self.new_api.add_books(
  File "/usr/lib/calibre/calibre/db/cache.py", line 1713, in add_books
    book_id = self.create_book_entry(mi, add_duplicates=add_duplicates, apply_import_tags=apply_import_tags, preserve_uuid=preserve_uuid)
  File "/usr/lib/calibre/calibre/db/cache.py", line 72, in call_func_with_lock
    return func(*args, **kwargs)
  File "/usr/lib/calibre/calibre/db/cache.py", line 1683, in create_book_entry
    self._set_metadata(book_id, mi, ignore_errors=True)
  File "/usr/lib/calibre/calibre/db/cache.py", line 1396, in set_metadata
    self._update_path({book_id})
  File "/usr/lib/calibre/calibre/db/cache.py", line 1220, in update_path
    self.backend.update_path(book_id, title, author, self.fields['path'], self.fields['formats'])
  File "/usr/lib/calibre/calibre/db/backend.py", line 1649, in update_path
    os.makedirs(tpath)
  File "/usr/lib/python3.9/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/lib/python3.9/os.py", line 225, in makedirs
    mkdir(name, mode)
ValueError: embedded null byte

**Comment by talebook** [comment]
文件名或作者名含有特殊字符
