### ISSUE TITLE
从calibre-web迁移过来，首页和导航栏的按作者分类点击后报错

### ISSUE THREAD

**Issue by ThermalEng** [talebook/talebook#263]
报错提示：
Exception:
Traceback (most recent call last):
  File "/var/www/talebook/webserver/handlers/base.py", line 50, in do
    rsp = func(self, *args, **kwargs)
  File "/var/www/talebook/webserver/handlers/meta.py", line 52, in get
    items = self.get_category_with_count(meta)
  File "/var/www/talebook/webserver/handlers/base.py", line 520, in get_category_with_count
    rows = self.cache.backend.conn.get(sql)
  File "/usr/lib/calibre/calibre/db/backend.py", line 364, in get
    return ans.fetchall()
apsw.CorruptError: CorruptError: database disk image is malformed

点击下方的”好的“无反应

图书管理界面中，作者正常显示

**Comment by talebook** [comment]
报错提示为：database disk image is malformed，数据库磁盘映像格式不正确。也就是数据库被损坏了。可能是磁盘空间不足等原因

**Comment by qbmiller** [comment]
johngong/calibre-web迁移。 数据库兼容吗， 原目录不用变？还是得从头拷贝一遍书籍
不需要考虑原先已读等
