### ISSUE TITLE
请问更新了近期版本后的报错, latest和Master上都会有错......网页界面的用户登陆口看不到了,书也打不开. 只有通过app的OPDS接入.

### ISSUE THREAD

**Issue by liuxingyulee** [talebook/talebook#275]
Exception:

Traceback (most recent call last):
  File "/var/www/talebook/webserver/handlers/base.py", line 51, in do
    rsp = func(self, *args, **kwargs)
  File "/var/www/talebook/webserver/handlers/user.py", line 239, in get
    user = self.current_user
  File "/usr/local/lib/python3.9/dist-packages/tornado/web.py", line 1340, in current_user
    self._current_user = self.get_current_user()
  File "/var/www/talebook/webserver/handlers/base.py", line 214, in get_current_user
    user_id = self.user_id()
  File "/var/www/talebook/webserver/handlers/base.py", line 207, in user_id
    login_time = self.get_secure_cookie("lt")
  File "/var/www/talebook/webserver/handlers/base.py", line 99, in get_secure_cookie
    self.cookies_cache[key] = super(BaseHandler, self).get_secure_cookie(key)
  File "/usr/local/lib/python3.9/dist-packages/tornado/web.py", line 771, in get_secure_cookie
    self.require_setting("cookie_secret", "secure cookies")
  File "/usr/local/lib/python3.9/dist-packages/tornado/web.py", line 1587, in require_setting
    raise Exception(
Exception: You must define the 'cookie_secret' setting in your application to use secure cookies

**Comment by liuxingyulee** [comment]
在点击一本书时,会报错如下:

Exception:

Traceback (most recent call last):
  File "/var/www/talebook/webserver/handlers/base.py", line 51, in do
    rsp = func(self, *args, **kwargs)
  File "/var/www/talebook/webserver/handlers/book.py", line 114, in get
    "book": utils.BookFormatter(self, book).format(with_files=True, with_perms=True),
  File "/var/www/talebook/webserver/utils.py", line 104, in format
    data.update(self.get_permissions())
  File "/var/www/talebook/webserver/utils.py", line 89, in get_permissions
    "is_owner": h.is_admin() or h.is_book_owner(self.book["id"], h.user_id()),
  File "/var/www/talebook/webserver/handlers/base.py", line 230, in is_admin
    if not self.current_user:
  File "/usr/local/lib/python3.9/dist-packages/tornado/web.py", line 1340, in current_user
    self._current_user = self.get_current_user()
  File "/var/www/talebook/webserver/handlers/base.py", line 214, in get_current_user
    user_id = self.user_id()
  File "/var/www/talebook/webserver/handlers/base.py", line 207, in user_id
    login_time = self.get_secure_cookie("lt")
  File "/var/www/talebook/webserver/handlers/base.py", line 99, in get_secure_cookie
    self.cookies_cache[key] = super(BaseHandler, self).get_secure_cookie(key)
  File "/usr/local/lib/python3.9/dist-packages/tornado/web.py", line 771, in get_secure_cookie
    self.require_setting("cookie_secret", "secure cookies")
  File "/usr/local/lib/python3.9/dist-packages/tornado/web.py", line 1587, in require_setting
    raise Exception(
Exception: You must define the 'cookie_secret' setting in your application to use secure cookies

尝试过更改所在书库的所有人chown/chmod, 但看起来问题没有解决

**Comment by talebook** [comment]
到管理员入口-高级配置项-cookie随机密钥中检查看下是否为空？填个随机字符串上去

**Comment by liuxingyulee** [comment]
谢谢Talebook回复, 问题是管理员入口在网页上也看不到了,重新做了几次container也是相同问题.
请问, 自己到容器中修改配置文件,可以用什么方式来 天津cookie随机密钥?
谢谢🙏

**Comment by liuxingyulee** [comment]
终于恢复了, 新建了一个docker, 然后books/settings/里所有配置文件,拷贝到损坏的docker里的books/settings/
就恢复配置了. 感谢开发者的提醒.
谢谢

**Comment by liuxingyulee** [comment]
终于恢复了, 新建了一个docker, 然后books/settings/里所有配置文件,拷贝到损坏的docker里的books/settings/
就恢复配置了. 感谢开发者的提醒.
谢谢
