### ISSUE TITLE
【Bug】更新到3.6.2后，进行后台扫描书籍，持续报错

### ISSUE THREAD

**Issue by Pan06da** [talebook/talebook#276]
Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/base.py", line 1964, in _exec_single_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/default.py", line 747, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: database is locked

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/www/talebook/webserver/handlers/base.py", line 51, in do
    rsp = func(self, *args, **kwargs)
  File "/var/www/talebook/webserver/handlers/base.py", line 85, in do
    if not self.current_user:
  File "/usr/local/lib/python3.9/dist-packages/tornado/web.py", line 1340, in current_user
    self._current_user = self.get_current_user()
  File "/var/www/talebook/webserver/handlers/base.py", line 217, in get_current_user
    user = self.session.query(Reader).get(user_id) if user_id else None
  File "", line 2, in get
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/util/deprecations.py", line 383, in warned
    return fn(*args, **kwargs)  # type: ignore[no-any-return]
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/query.py", line 1130, in get
    return self._get_impl(ident, loading.load_on_pk_identity)
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/query.py", line 1139, in _get_impl
    return self.session._get_impl(
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/session.py", line 3670, in _get_impl
    return db_load_fn(
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/loading.py", line 670, in load_on_pk_identity
    session.execute(
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/session.py", line 2229, in execute
    return self._execute_internal(
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/session.py", line 2124, in _execute_internal
    result: Result[Any] = compile_state_cls.orm_execute_statement(
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/context.py", line 253, in orm_execute_statement
    result = conn.execute(
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/base.py", line 1414, in execute
    return meth(
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/sql/elements.py", line 485, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/base.py", line 1638, in _execute_clauseelement
    ret = self._execute_context(
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/base.py", line 1842, in _execute_context
    return self._exec_single_context(
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/base.py", line 1983, in _exec_single_context
    self._handle_dbapi_exception(
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/base.py", line 2325, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/base.py", line 1964, in _exec_single_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/default.py", line 747, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database is locked
[SQL: SELECT readers.id AS readers_id, readers.username AS readers_username, readers.password AS readers_password, readers.salt AS readers_salt, readers.name AS readers_name, readers.email AS readers_email, readers.avatar AS readers_avatar, readers.admin AS readers_admin, readers.active AS readers_active, readers.permission AS readers_permission, readers.create_time AS readers_create_time, readers.update_time AS readers_update_time, readers.access_time AS readers_access_time, readers.extra AS readers_extra 
FROM readers 
WHERE readers.id = ?]
[parameters: (1,)]
(Background on this error at: https://sqlalche.me/e/20/e3q8)

**Comment by talebook** [comment]
`sqlite3.OperationalError: database is locked` 数据库被锁住了。可以先试试重启整个容器，应该能释放锁。本质原因是代码中对于并发处理不够严谨，可能有竞争状态，后面再细细优化下。

**Comment by HelloMusician** [comment]
> `sqlite3.OperationalError: database is locked`数据库被锁住了。可以先试试重启整个容器，应该能释放锁。本质原因是代码中对于并发处理不够严谨，可能有竞争状态，后面再细细优化下。

我部署完导入了13本，没有问题，刚才一次性导入1W多本，也是提示数据库被锁
