### ISSUE TITLE
为什么不能在线阅读PDF？

### ISSUE THREAD

**Issue by xiaobaixuejava** [talebook/talebook#287]
每次点击在线阅读都是下载，看了下日志有报错

页面显示   500: Internal Server Error

**Comment by xiaobaixuejava** [comment]
Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/base.py", line 1964, in _exec_single_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/default.py", line 747, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: database is locked

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/www/talebook/webserver/handlers/base.py", line 51, in do
    rsp = func(self, *args, **kwargs)
  File "/var/www/talebook/webserver/handlers/base.py", line 89, in do
    return func(self, *args, **kwargs)
  File "/var/www/talebook/webserver/handlers/scan.py", line 351, in post
    count = m.delete(hashlist)
  File "/var/www/talebook/webserver/handlers/scan.py", line 165, in delete
    count = query.delete()
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/query.py", line 3191, in delete
    self.session.execute(
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/session.py", line 2229, in execute
    return self._execute_internal(
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/session.py", line 2124, in _execute_internal
    result: Result[Any] = compile_state_cls.orm_execute_statement(
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/bulk_persistence.py", line 1838, in orm_execute_statement
    return super().orm_execute_statement(
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/context.py", line 253, in orm_execute_statement
    result = conn.execute(
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/base.py", line 1414, in execute
    return meth(
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/sql/elements.py", line 485, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/base.py", line 1638, in _execute_clauseelement
    ret = self._execute_context(
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/base.py", line 1842, in _execute_context
    return self._exec_single_context(
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/base.py", line 1983, in _exec_single_context
    self._handle_dbapi_exception(
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/base.py", line 2325, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/base.py", line 1964, in _exec_single_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/default.py", line 747, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database is locked
[SQL: DELETE FROM scanfiles WHERE scanfiles.hash IN (?)]
[parameters: ('sha256:47f36a120242362b93db1d7726fd1799f8a7eb41406bba4f49f110aa6cb14d6e',)]
(Background on this error at: https://sqlalche.me/e/20/e3q8)

**Comment by li-oldman** [comment]
database is locked 数据库在操作，被锁了，您是不是在上传书籍或者扫描书籍。等待扫描上传完再继续，或者重启下。

**Comment by shentar** [comment]
有地方并发没控制好，可以重启一次容器能缓解。也可以等上面那个session泄露的issue解决。

**Comment by xiaobaixuejava** [comment]
不是数据库锁的问题，我重启后依然有这个问题出现，打开在线阅读就是 500: Internal Server Error，感觉问题可能在扫描添加数据库或者读取方法上有问题导致，你可以导入pdf试试看，重新安装镜像你打开内置的那个pdf文件也会出现这个问题

**Comment by xiaobaixuejava** [comment]
[talebook.log](https://github.com/talebook/talebook/files/11072065/talebook.log)   这是talebook的日志，里面有sql错误等等。。。

**Comment by xiaobaixuejava** [comment]
我用koodo 看同一个pdf就好好的，期望能早点解决吧    比心！比心！比心！

**Comment by xiaobaixuejava** [comment]
这个问题只在打开pdf的时候出现，导入可以成功导入就是不能在线观看，其他格式的我在线观看没有问题，即使你是第一次安装镜像，打开内置的pdf测试文件也是不可阅读

**Comment by shentar** [comment]
> 这个问题只在打开pdf的时候出现，导入可以成功导入就是不能在线观看，其他格式的我在线观看没有问题，即使你是第一次安装镜像，打开内置的pdf测试文件也是不可阅读

着急的话可以先用这个镜像顶一下：https://hub.docker.com/r/shentar/talebook，解决了db被锁的问题。

**Comment by xiaobaixuejava** [comment]
> > 这个问题只在打开pdf的时候出现，导入可以成功导入就是不能在线观看，其他格式的我在线观看没有问题，即使你是第一次安装镜像，打开内置的pdf测试文件也是不可阅读
> 
> 着急的话可以先用这个镜像顶一下：https://hub.docker.com/r/shentar/talebook 解决了db被锁的问题。

我试了下pdf可以正常打开，非常感谢，不过问一下他这个进度保存是怎样运作的？是保存在浏览器缓存中而不是服务端吗？我在edge浏览器打开 关闭后，在safari浏览器中查看发现还是从头阅读的

**Comment by shentar** [comment]
是的，是在浏览器端保存的，是pdf.js这个组件做的，估计二者共用了cookies。

**Comment by HelloMusician** [comment]
我的pdf可以正常阅读啊，把浏览器自动下载屏蔽这个站点就行了

**Comment by suka233333** [comment]
具体可以看这篇文章，似乎可以完美解决：
https://www.frank9.com/pdfjs-failed-to-fetch.html

**Comment by HelloMusician** [comment]
感谢！

Suka ***@***.***> 于2023年9月10日周日 16:29写道：
