### ISSUE TITLE
文石OPDS无法下载书籍文件

### ISSUE THREAD

**Issue by lim0513** [talebook/talebook#288]
使用程序为docker latest 版本，报错信息如下：

```
[E 230405 08:42:47 web:1789] Uncaught exception GET /opds/nav/4f6e6577657374/api/book/19.epub?from=opds (240e:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx)
    HTTPServerRequest(protocol='http', host='books.xxxxx.xxx:5000', method='GET', uri='/opds/nav/4f6e6577657374/api/book/19.epub?from=opds', version='HTTP/1.0', remote_ip='240e:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx')
    Traceback (most recent call last):
      File "/usr/local/lib/python3.9/dist-packages/tornado/web.py", line 1702, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/var/www/talebook/webserver/handlers/opds.py", line 741, in get
        self.write(self.opds_navcatalog(which, offset=offset))
      File "/var/www/talebook/webserver/handlers/opds.py", line 574, in opds_navcatalog
        which = unhexlify(which)
      File "/var/www/talebook/webserver/handlers/opds.py", line 109, in unhexlify
        return binascii.unhexlify(x).decode("utf-8")
    binascii.Error: Odd-length string
[E 230405 08:42:47 web:2239] 500 GET /opds/nav/4f6e6577657374/api/book/19.epub?from=opds (240e:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx) 2.31ms
```

**Comment by talebook** [comment]
跟阅读器无关，是书籍本身问题，字符串编码有异常
