### ISSUE TITLE
[Bug]: 用户注册及刮削问题

### ISSUE THREAD

**Issue by unlimited996** [talebook/talebook#290]
1.用户使用不存在的邮箱注册后异常没有正确处理，而且该用户数据被存入了数据库
2.用户注册后无需点击激活链接就能直接登录，没看懂发的这个链接有什么用
3.百度的刮削完全没有用，能不能提供个配置来移除
4.豆瓣的刮削需要一个测试按钮以判断是否可用，以及使用无效链接尝试读取刮削数据的时候会导致线程卡住(接口返回异常前页面无响应)
![Screenshot_20230409_100326_com huawei browser](https://user-images.githubusercontent.com/79558585/230750665-5629dab8-47a7-4217-b157-3626fd992827.jpg)
![Screenshot_20230409_100523_com huawei browser](https://user-images.githubusercontent.com/79558585/230750667-cc180537-d012-4fc0-ba5d-0355aa46da53.jpg)

**Comment by unlimited996** [comment]
完整异常如下
Exception:<br><pre style="white-space:pre-wrap;word-break:keep-all">Traceback (most recent call last): File "/var/www/talebook/webserver/handlers/base.py", line 51, in do rsp = func(self, *args, **kwargs) File "/var/www/talebook/webserver/handlers/user.py", line 151, in post self.send_active_email(user) File "/var/www/talebook/webserver/handlers/user.py", line 112, in send_active_email self.mail(mail_from, mail_to, mail_subject, mail_body) File "/var/www/talebook/webserver/handlers/base.py", line 517, in mail sendmail( File "/usr/lib/calibre/calibre/utils/smtp.py", line 191, in sendmail s.sendmail(from_, to, msg) File "/usr/lib/python3.9/smtplib.py", line 892, in sendmail raise SMTPDataError(code, resp) smtplib.SMTPDataError: (550, b'The recipient may contain a non-existent account, please check the recipient address.') </pre>
Exception:
Traceback (most recent call last):
  File "/var/www/talebook/webserver/handlers/base.py", line 51, in do
    rsp = func(self, *args, **kwargs)
  File "/var/www/talebook/webserver/handlers/user.py", line 151, in post
    self.send_active_email(user)
  File "/var/www/talebook/webserver/handlers/user.py", line 112, in send_active_email
    self.mail(mail_from, mail_to, mail_subject, mail_body)
  File "/var/www/talebook/webserver/handlers/base.py", line 517, in mail
    sendmail(
  File "/usr/lib/calibre/calibre/utils/smtp.py", line 191, in sendmail
    s.sendmail(from_, to, msg)
  File "/usr/lib/python3.9/smtplib.py", line 892, in sendmail
    raise SMTPDataError(code, resp)
smtplib.SMTPDataError: (550, b'The recipient may contain a non-existent account, please check the recipient address.')

**Comment by abovo484** [comment]
注册提示错误，但是用户可以登入
Exception:
Traceback (most recent call last):
  File "/var/www/talebook/webserver/handlers/base.py", line 51, in do
    rsp = func(self, *args, **kwargs)
  File "/var/www/talebook/webserver/handlers/user.py", line 151, in post
    self.send_active_email(user)
  File "/var/www/talebook/webserver/handlers/user.py", line 112, in send_active_email
    self.mail(mail_from, mail_to, mail_subject, mail_body)
  File "/var/www/talebook/webserver/handlers/base.py", line 517, in mail
    sendmail(
  File "/usr/lib/calibre/calibre/utils/smtp.py", line 188, in sendmail
    s.login(username, password)
  File "/usr/lib/python3.9/smtplib.py", line 734, in login
    raise last_exception
  File "/usr/lib/python3.9/smtplib.py", line 723, in login
    (code, resp) = self.auth(
  File "/usr/lib/python3.9/smtplib.py", line 646, in auth
    raise SMTPAuthenticationError(code, resp)
smtplib.SMTPAuthenticationError: (535, b'Login Fail. Please enter your authorization code to login. More information in http://service.mail.qq.com/cgi-bin/help?subtype=1&&id=28&&no=1001256')

**Comment by unlimited996** [comment]
版本更新后更新了下服务，发现新功能在解析(异常？)时候会导致服务无响应(页面连接超时)，这个功能如果不报错的话很好用，麻烦处理下这个问题或者提供个开关关闭这个功能，另外还发现注册入口关闭的情况下把url后缀改成 /signup 的话还是能访问注册页面……
