### ISSUE TITLE
发送激活邮件报错

### ISSUE THREAD

**Issue by Dai-MoeWolf** [talebook/talebook#292]
Exception:
Traceback (most recent call last):
  File "/var/www/talebook/webserver/handlers/base.py", line 51, in do
    rsp = func(self, *args, **kwargs)
  File "/var/www/talebook/webserver/handlers/base.py", line 78, in do
    return func(self, *args, **kwargs)
  File "/var/www/talebook/webserver/handlers/user.py", line 159, in get
    self.send_active_email(self.current_user)
  File "/var/www/talebook/webserver/handlers/user.py", line 112, in send_active_email
    self.mail(mail_from, mail_to, mail_subject, mail_body)
  File "/var/www/talebook/webserver/handlers/base.py", line 517, in mail
    sendmail(
  File "/usr/lib/calibre/calibre/utils/smtp.py", line 188, in sendmail
    s.login(username, password)
  File "/usr/lib/python3.9/smtplib.py", line 734, in login
    raise last_exception
  File "/usr/lib/python3.9/smtplib.py", line 723, in login
    (code, resp) = self.auth(
  File "/usr/lib/python3.9/smtplib.py", line 646, in auth
    raise SMTPAuthenticationError(code, resp)
smtplib.SMTPAuthenticationError: (535, b'Login Fail. Please enter your authorization code to login. More information in http://service.mail.qq.com/cgi-bin/help?subtype=1&&id=28&&no=1001256')

**Comment by talebook** [comment]
这个是邮件账号配置问题。按照文档指引更正信息就好。
