### ISSUE TITLE
批量导入书籍UnicodeEncodeError: 'ascii'报错

### ISSUE THREAD

**Issue by a87750530** [talebook/talebook#30]
报错代码如下
root@dfsdsd:/# calibredb add --library-path=/data/books/library/ -r /data/books/upload/mobi/
The following books were not added as they already exist in the database (see --duplicates option):
Traceback (most recent call last):
  File "/usr/bin/calibredb", line 20, in <module>
    sys.exit(main())
  File "/usr/lib/calibre/calibre/library/cli.py", line 1642, in main
    return command(args[2:], dbpath)
  File "/usr/lib/calibre/calibre/library/cli.py", line 471, in command_add
    tags, opts.series, opts.series_index, opts.cover, identifiers, lcodes, opts.filters)
  File "/usr/lib/calibre/calibre/library/cli.py", line 345, in do_add
    title = title.encode(preferred_encoding)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-6: ordinal not in range(128)

建议修复方式
import sys
reload(sys)
sys.setdefaultencoding('utf8')

**Comment by talebook** [comment]
请提供下报错的书籍文件，我验证下

**Comment by Eric-xin** [comment]
怎么解决？还是不行

**Comment by KITblue** [comment]
批量导入可否做成带UI的

**Comment by a87750530** [comment]
> 批量引入可否干涉带UI的

好像不可以，老版本站长已经不更新了

**Comment by jian-lan** [comment]
同样的问题，希望尽快修复一下
root@calibre-webserver-1:~# calibredb add --library-path=/data/books/library/ -r /data/books/upload/mobi/
The following books were not added as they already exist in the database (see --duplicates option):
Traceback (most recent call last):
  File "/usr/bin/calibredb", line 20, in <module>
    sys.exit(main())
  File "/usr/lib/calibre/calibre/library/cli.py", line 1709, in main
    return command(args[2:], dbpath)
  File "/usr/lib/calibre/calibre/library/cli.py", line 487, in command_add
    tags, opts.series, opts.series_index, opts.cover, identifiers, lcodes, opts.filters)
  File "/usr/lib/calibre/calibre/library/cli.py", line 356, in do_add
    title = title.encode(preferred_encoding)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-10: ordinal not in range(128)

试图导入的文件附上一个
[现代推理馆东野圭吾系列(套装共3册).mobi.zip](https://github.com/talebook/calibre-webserver/files/5992608/3.mobi.zip)

**Comment by talebook** [comment]
`v3.5.6`版本支持了批量导入图书的界面操作；zip包里的书籍试了下能正常导入。时隔两年，终于可以关单了
