### ISSUE TITLE
Mobi解压失败。

### ISSUE THREAD

**Issue by TheLonelinessOfHS** [talebook/talebook#302]
[I 230513 20:35:52 book:549] convert book: /data/books/library/小桥老树/官场笔记 (14)/官场笔记 - 小桥老树.mobi => /data/books/convert/book-14-1684010152.epub, progress: /data/books/progress/progress-14.log
[I 230513 20:35:52 book:62] CMD: 'ebook-convert' '/data/books/library/小桥老树/官场笔记 (14)/官场笔记 - 小桥老树.mobi' '/data/books/convert/book-14-1684010152.epub' '--flow-size' '0'
[D 230513 20:35:52 base:332] create template env for [/var/www/talebook/webserver/resources]
[E 230513 20:35:52 web:2990] Could not open static file '/var/www/talebook/webserver/resources/readium/css/bootstrap.css'
[E 230513 20:35:52 web:2990] Could not open static file '/var/www/talebook/webserver/resources/readium/css/viewer.css'
[E 230513 20:35:52 web:2990] Could not open static file '/var/www/talebook/webserver/resources/readium/css/readium_js.css'
[E 230513 20:35:52 web:2990] Could not open static file '/var/www/talebook/webserver/resources/js/jquery-1.11.1.min.js'
[E 230513 20:35:52 web:2990] Could not open static file '/var/www/talebook/webserver/resources/readium/lib/require.js'
[E 230513 20:35:52 web:2990] Could not open static file '/var/www/talebook/webserver/resources/readium/lib/ReadiumViewerLite.js'
[E 230513 20:35:52 web:2990] Could not open static file '/var/www/talebook/webserver/resources/readium/require_config.js'
[E 230513 20:35:52 web:2990] Could not open static file '/var/www/talebook/webserver/resources/readium/css/annotations.css'
[I 230513 20:35:52 web:2239] 200 GET /read/14 (172.70.86.16) 30.00ms
[I 230513 20:35:52 book:66] ebook-convert finish: /data/books/convert/book-14-1684010152.epub, err: Traceback (most recent call last):
      File "/usr/bin/ebook-convert", line 20, in <module>
        sys.exit(main())
      File "/usr/lib/calibre/calibre/ebooks/conversion/cli.py", line 401, in main
        plumber.run()
      File "/usr/lib/calibre/calibre/ebooks/conversion/plumber.py", line 1108, in run
        self.oeb = self.input_plugin(stream, self.opts,
      File "/usr/lib/calibre/calibre/customize/conversion.py", line 245, in __call__
        ret = self.convert(stream, options, file_ext,
      File "/usr/lib/calibre/calibre/ebooks/conversion/plugins/mobi_input.py", line 47, in convert
        opf = os.path.abspath(mr())
      File "/usr/lib/calibre/calibre/ebooks/mobi/reader/mobi8.py", line 99, in __call__
        self.processed_records = self.mobi6_reader.extract_text(offset=offset)
      File "/usr/lib/calibre/calibre/ebooks/mobi/reader/mobi6.py", line 802, in extract_text
        text_sections = [self.text_section(i) for i in range(offset,
      File "/usr/lib/calibre/calibre/ebooks/mobi/reader/mobi6.py", line 802, in <listcomp>
        text_sections = [self.text_section(i) for i in range(offset,
      File "/usr/lib/calibre/calibre/ebooks/mobi/reader/mobi6.py", line 797, in text_section
        trail_size = self.sizeof_trailing_entries(data)
      File "/usr/lib/calibre/calibre/ebooks/mobi/reader/mobi6.py", line 780, in sizeof_trailing_entries
        num += sizeof_trailing_entry(data, size - num)
      File "/usr/lib/calibre/calibre/ebooks/mobi/reader/mobi6.py", line 767, in sizeof_trailing_entry
        v = ord(ptr[psize-1:psize])
    TypeError: ord() expected a character, but string of length 0 found

[E 230513 20:35:52 book:38] Failed to run background task:
[E 230513 20:35:52 book:39] Traceback (most recent call last):
      File "/var/www/talebook/webserver/handlers/book.py", line 33, in worker
        func(*args, **kwargs)
      File "/var/www/talebook/webserver/handlers/book.py", line 557, in extract_book
        with open(new_path, "rb") as f:
    FileNotFoundError: [Errno 2] No such file or directory: '/data/books/convert/book-14-1684010152.epub'

疑似calibre的问题

**Comment by talebook** [comment]
是calibre自身的问题。无法解决。
