### ISSUE TITLE
【bug】可以从豆瓣获取API获取【书籍信息】，同时点击获取【书籍信息与图片】则报错

### ISSUE THREAD

**Issue by Pan06da** [talebook/talebook#320]
Exception:
Traceback (most recent call last):
  File "/var/www/talebook/webserver/handlers/base.py", line 51, in do
    rsp = func(self, *args, **kwargs)
  File "/var/www/talebook/webserver/handlers/base.py", line 78, in do
    return func(self, *args, **kwargs)
  File "/var/www/talebook/webserver/handlers/book.py", line 258, in post
    self.db.set_metadata(book_id, mi)
  File "/usr/lib/calibre/calibre/db/legacy.py", line 581, in set_metadata
    self.new_api.set_metadata(book_id, mi, ignore_errors=ignore_errors, set_title=set_title, set_authors=set_authors, force_changes=force_changes)
  File "/usr/lib/calibre/calibre/db/cache.py", line 72, in call_func_with_lock
    return func(*args, **kwargs)
  File "/usr/lib/calibre/calibre/db/cache.py", line 1414, in set_metadata
    self._set_cover({book_id: cdata})
  File "/usr/lib/calibre/calibre/db/cache.py", line 1337, in set_cover
    self.backend.set_cover(book_id, path, data)
  File "/usr/lib/calibre/calibre/db/backend.py", line 1515, in set_cover
    save_cover_data_to(data, path)
  File "/usr/lib/calibre/calibre/utils/img.py", line 289, in save_cover_data_to
    f.write(image_to_data(img, compression_quality, fmt, compression_quality // 10) if changed else data)
  File "/usr/lib/calibre/calibre/utils/img.py", line 197, in image_to_data
    raise ValueError('Failed to export image as ' + fmt + ' with error: ' + w.errorString())
ValueError: Failed to export image as JPEG with error: Image is empty

**Comment by talebook** [comment]
需要提供下具体的数据，才能查清楚当时的图片为何为空白。先关单
