### ISSUE TITLE
无法发送激活邮件

### ISSUE THREAD

**Issue by luo-chuan** [talebook/talebook#324]
文渊阁，提示错误信息
```
Exception:
Traceback (most recent call last):
  File "/var/www/talebook/webserver/handlers/base.py", line 51, in do
    rsp = func(self, *args, **kwargs)
  File "/var/www/talebook/webserver/handlers/base.py", line 78, in do
    return func(self, *args, **kwargs)
  File "/var/www/talebook/webserver/handlers/user.py", line 159, in get
    self.send_active_email(self.current_user)
  File "/var/www/talebook/webserver/handlers/user.py", line 112, in send_active_email
    self.mail(mail_from, mail_to, mail_subject, mail_body)
  File "/var/www/talebook/webserver/handlers/base.py", line 517, in mail
    sendmail(
  File "/usr/lib/calibre/calibre/utils/smtp.py", line 188, in sendmail
    s.login(username, password)
  File "/usr/lib/python3.9/smtplib.py", line 723, in login
    (code, resp) = self.auth(
  File "/usr/lib/python3.9/smtplib.py", line 635, in auth
    (code, resp) = self.docmd("AUTH", mechanism + " " + response)
  File "/usr/lib/python3.9/smtplib.py", line 425, in docmd
    return self.getreply()
  File "/usr/lib/python3.9/smtplib.py", line 398, in getreply
    raise SMTPServerDisconnected("Connection unexpectedly closed")
smtplib.SMTPServerDisconnected: Connection unexpectedly closed
```

**Comment by w211691** [comment]
密码换成16位安全码试试？

**Comment by HallowJuan** [comment]
老哥你激活成功了吗。我今儿也遇到这个问题了

**Comment by w211691** [comment]
> 老哥你激活成功了吗。我今天儿也遇到这个问题了

可以激活成功，我用的QQ邮箱，按照smtp.qq.com设置就行了，密码是16位随机密码，QQ邮箱里能看
