### ISSUE TITLE
修改标签时出错

### ISSUE THREAD

**Issue by surenet** [talebook/talebook#332]
Exception:
Traceback (most recent call last):
  File "/var/www/talebook/webserver/handlers/base.py", line 51, in do
    rsp = func(self, *args, **kwargs)
  File "/var/www/talebook/webserver/handlers/base.py", line 78, in do
    return func(self, *args, **kwargs)
  File "/var/www/talebook/webserver/handlers/book.py", line 301, in post
    self.db.set_metadata(bid, mi)
  File "/usr/lib/calibre/calibre/db/legacy.py", line 581, in set_metadata
    self.new_api.set_metadata(book_id, mi, ignore_errors=ignore_errors, set_title=set_title, set_authors=set_authors, force_changes=force_changes)
  File "/usr/lib/calibre/calibre/db/cache.py", line 72, in call_func_with_lock
    return func(*args, **kwargs)
  File "/usr/lib/calibre/calibre/db/cache.py", line 1383, in set_metadata
    set_field('title', mi.title)
  File "/usr/lib/calibre/calibre/db/cache.py", line 1378, in set_field
    dirtied.update(self._set_field(name, {book_id:val}, do_path_update=False, allow_case_change=allow_case_change))
  File "/usr/lib/calibre/calibre/db/cache.py", line 1198, in set_field
    dirtied = f.writer.set_books(
  File "/usr/lib/calibre/calibre/db/write.py", line 543, in set_books
    dirtied = self.set_books_func(book_id_val_map, db, self.field,
  File "/usr/lib/calibre/calibre/db/write.py", line 211, in set_title
    field.title_sort_field.writer.set_books(
  File "/usr/lib/calibre/calibre/db/write.py", line 543, in set_books
    dirtied = self.set_books_func(book_id_val_map, db, self.field,
  File "/usr/lib/calibre/calibre/db/write.py", line 197, in one_one_in_books
    db.executemany(
  File "/usr/lib/calibre/calibre/db/backend.py", line 932, in executemany
    return self.conn.cursor().executemany(sql, sequence_of_bindings)
apsw.ReadOnlyError: ReadOnlyError: attempt to write a readonly database

**Comment by talebook** [comment]
无他，但重启尔
