### ISSUE TITLE
书籍数据库为空时页面无法加载

### ISSUE THREAD

**Issue by timlee0212** [talebook/talebook#363]
# 问题描述
当书籍数据库为空时，网页无法打开

# 问题环境
- URL：出现异常时的URL
- 运行系统：Docker
- 访问设备：Ubuntu 22.04 
- 浏览器版本：Chrome 121.0.6167.87

# 复现步骤
1. 根据提示安装Talebook
2. 删除所有自带的示例书籍
3. 刷新页面

# 截图
![image](https://github.com/talebook/talebook/assets/22514478/96641a25-f5e0-440e-afa7-83a4cc48f778)
页面保持这个状态

# 报错信息
把系统上提示的报错信息文字版粘贴出来

# 日志

> [I 240201 13:56:10 main:127] Init library with [/data/books/library]
> [I 240201 13:56:10 main:128] Init AuthDB  with [sqlite:////data/books/calibre-webserver.db]
> [I 240201 13:56:10 main:129] Init Static  with [/var/www/talebook/webserver/resources]
> [I 240201 13:56:10 main:130] Init HTML    with [/var/www/talebook/webserver/../app/dist]
> [I 240201 13:56:10 main:131] Init Nuxtjs  with [/var/www/talebook/webserver/../app/.env]
> [I 240201 13:56:10 models:40] Bind modles._session()
> [I 240201 13:56:11 main:194] Now, Running...
> [E 240201 13:56:11 async_service:88] service register <send_mail>
> [E 240201 13:56:11 async_service:88] service register <send_book>
> [E 240201 13:56:11 async_service:88] service register <convert_and_send>
> [E 240201 13:56:11 async_service:88] service register <convert_and_save>
> [E 240201 13:56:11 async_service:88] service register <parse_txt_content>
> [E 240201 13:56:11 async_service:88] service register <do_scan>
> [E 240201 13:56:11 async_service:88] service register <do_import>
> [D 240201 13:56:11 selector_events:59] Using selector: EpollSelector
> [E 240201 13:56:18 base:54] Traceback (most recent call last):
>       File "/var/www/talebook/webserver/handlers/base.py", line 49, in do
>         rsp = func(self, *args, **kwargs)
>       File "/var/www/talebook/webserver/handlers/book.py", line 40, in get
>         raise web.HTTPError(404, reason=_(u"本书库暂无藏书"))
>     tornado.web.HTTPError: HTTP 404: 本书库暂无藏书
> 
> [I 240201 13:56:18 web:2348] 200 GET /api/index?random=12&recent=12 (192.168.1.245) 3.49ms

# 其他

**Comment by zackfan** [comment]
同样遇到，真是神仙bug，没书还不行，你咋解决的
