### ISSUE TITLE
群晖docker安装，一直显示服务器正在启动中

### ISSUE THREAD

**Issue by pomolnc** [talebook/talebook#364]
# 问题描述
一直显示服务器正在启动中

# 问题环境
- 运行系统：群晖
- 访问设备：Windows
- 浏览器版本：Microsoft Edge 版本 121.0.2277.98 (正式版本) (64 位)

# 复现步骤
使用docker-compose和docker命令拉取启动都出现此问题

# 截图
![screenshot-20240207-102921](https://github.com/talebook/talebook/assets/24970905/682e1005-0e1a-4ad2-a489-af7cff60d7e0)

# 报错信息
把系统上提示的报错信息文字版粘贴出来

# 日志
INFO:root:Init library with [/data/books/library]
INFO:root:Init AuthDB  with [sqlite:////data/books/calibre-webserver.db]
INFO:root:Init Static  with [/var/www/talebook/webserver/resources]
INFO:root:Init HTML    with [/var/www/talebook/webserver/../app/dist]
INFO:root:Init Nuxtjs  with [/var/www/talebook/webserver/../app/.env]
INFO:root:Bind modles._session()
Traceback (most recent call last):
  File "/var/www/talebook/server.py", line 13, in <module>
    sys.exit(webserver.main.main())
  File "/var/www/talebook/webserver/main.py", line 219, in main
    app = make_app()
  File "/var/www/talebook/webserver/main.py", line 158, in make_app
    book_db = LibraryDatabase(os.path.expanduser(options.with_library))
  File "/usr/lib/calibre/calibre/db/legacy.py", line 188, in __init__
    backend = self.backend = create_backend(library_path, default_prefs=default_prefs,
  File "/usr/lib/calibre/calibre/db/legacy.py", line 45, in create_backend
    return DB(library_path, default_prefs=default_prefs,
  File "/usr/lib/calibre/calibre/db/backend.py", line 443, in __init__
    os.makedirs(os.path.dirname(self.dbpath))
  File "/usr/lib/python3.9/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/lib/python3.9/os.py", line 225, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/data/books'
ERROR:root:Traceback (most recent call last):
  File "/var/www/talebook/webserver/loader.py", line 40, in loadfile
    import auto
ModuleNotFoundError: No module named 'auto'

**Comment by li-oldman** [comment]
PermissionError: [Errno 13] Permission denied: '/data/books'
权限问题，你的文件目录权限没设置好

**Comment by pomolnc** [comment]
> PermissionError: [Errno 13] Permission denied: '/data/books' 权限问题，你的文件目录权限没设置好

设置所有用户可读写了。。。换成shentar/talebook这个镜像就可以了
