### ISSUE TITLE
批量导入时，书名含有空格的时候，会报错无响应

### ISSUE THREAD

**Issue by Yxu-github** [talebook/talebook#368]
# 问题描述
批量导入时，书名含有空格的时候，会报错无响应

# 报错信息
[I 240124 01:23:27 scan:231] import [硅谷禁书  三  吸引力法则 ] from /data/books/imports/kindle人电子书/kindle人电子书合集/kindleren自购1-93/ZG005/硅谷禁书/硅谷禁书III-吸引力法则.pdf
Exception in thread do_import:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/var/www/talebook/webserver/handlers/scan.py", line 232, in do_import
    row.book_id = self.db.import_book(mi, [fpath])
  File "/usr/lib/calibre/calibre/db/legacy.py", line 362, in import_book
    book_ids, duplicates = self.new_api.add_books(
  File "/usr/lib/calibre/calibre/db/cache.py", line 1713, in add_books
    book_id = self.create_book_entry(mi, add_duplicates=add_duplicates, apply_import_tags=apply_import_tags, preserve_uuid=preserve_uuid)
  File "/usr/lib/calibre/calibre/db/cache.py", line 72, in call_func_with_lock
    return func(*args, **kwargs)
  File "/usr/lib/calibre/calibre/db/cache.py", line 1683, in create_book_entry
    self._set_metadata(book_id, mi, ignore_errors=True)
  File "/usr/lib/calibre/calibre/db/cache.py", line 1396, in set_metadata
    self._update_path({book_id})
  File "/usr/lib/calibre/calibre/db/cache.py", line 1220, in update_path
    self.backend.update_path(book_id, title, author, self.fields['path'], self.fields['formats'])
  File "/usr/lib/calibre/calibre/db/backend.py", line 1649, in update_path
    os.makedirs(tpath)
  File "/usr/lib/python3.9/os.py", line 225, in makedirs
    mkdir(name, mode)
ValueError: embedded null byte

**Comment by talebook** [comment]
这个问题之前有人反馈过 #304 ，已经修复了的。你可以升级到 v3.6.8 试试
