### ISSUE TITLE
opds 书库无法打开【By Newest】【By Title】【By Author】三个排序，显示500:Internal Server Error

### ISSUE THREAD

**Issue by Huster1993** [talebook/talebook#378]
# 问题描述
opds 书库无法打开【By Newest】【By Title】【By Author】三个排序，显示500:Internal Server Error

# 问题环境
- 版本号：例如v3.6.0
- URL：出现异常时的URL
- 运行系统：NAS/DOCKER
- 访问设备：iPhone/Android
- 浏览器版本：Safari
- 书籍信息：如果是特定的书异常，请提供「书名」和「作者名」

# 复现步骤
使用 静读天下v9.2 或者kybook 3 添加http://192.XXXXX:XXXX/opds/，之后打开如上所示三个排序，显示500错误，其他不会

# 截图
![image](https://github.com/talebook/talebook/assets/15936574/c2edd88e-8cfa-42c6-820c-6aaa6072b77f)
![image](https://github.com/talebook/talebook/assets/15936574/4442dbc6-9081-415d-9d93-6898954f1d2d)

# 报错信息
把系统上提示的报错信息文字版粘贴出来

# 日志
`    Traceback (most recent call last):
      File "/usr/local/lib/python3.9/dist-packages/tornado/web.py", line 1702, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/var/www/talebook/webserver/handlers/opds.py", line 741, in get
        self.write(self.opds_navcatalog(which, offset=offset))
      File "/var/www/talebook/webserver/handlers/opds.py", line 578, in opds_navcatalog
        return self.get_opds_all_books(which, page_url, up_url, offset=offset)
      File "/var/www/talebook/webserver/handlers/opds.py", line 498, in get_opds_all_books
        return self.get_opds_acquisition_feed(
      File "/var/www/talebook/webserver/handlers/opds.py", line 459, in get_opds_acquisition_feed
        AcquisitionFeed(
      File "/var/www/talebook/webserver/handlers/opds.py", line 399, in __init__
        self.root.append(ACQUISITION_ENTRY(item, db, updated, CFM, CKEYS, prefix))
      File "/var/www/talebook/webserver/handlers/opds.py", line 286, in ACQUISITION_ENTRY
        ans = E.entry(TITLE(title), E.author(E.name(authors)), ID(id_), UPDATED(updated))
      File "src/lxml/builder.py", line 228, in lxml.builder.ElementMaker.__call__
      File "src/lxml/builder.py", line 177, in lxml.builder.ElementMaker.__init__.add_text
      File "src/lxml/etree.pyx", line 1024, in lxml.etree._Element.text.__set__
      File "src/lxml/apihelpers.pxi", line 747, in lxml.etree._setNodeText
      File "src/lxml/apihelpers.pxi", line 735, in lxml.etree._createTextNode
      File "src/lxml/apihelpers.pxi", line 1540, in lxml.etree._utf8
    ValueError: All strings must be XML compatible: Unicode or ASCII, no NULL bytes or control characters
[E 240323 04:07:21 web:2239] 500 GET /opds/nav/4f7469746c65 (172.17.0.1) 232.87ms
[D 240323 04:10:54 base:218] Query User(1) = <id=1, username=admin, email=XXX@qq.com>
[I 240323 04:10:54 web:2239] 304 GET /api/admin/settings (172.17.0.1) 89.76ms
[D 240323 04:15:55 base:218] Query User(1) = <id=1, username=admin, email=XXX@qq.com>
[E 240323 04:15:55 loader:72] saving settings file: /data/books/settings/auto.py
[I 240323 04:15:55 web:2239] 200 POST /api/admin/settings (172.17.0.1) 127.84ms
[I 240323 04:15:55 autoreload:201] /data/books/settings/auto.py modified; restarting server
[I 240323 04:15:57 main:126] Init library with [/data/books/library]
[I 240323 04:15:57 main:127] Init AuthDB  with [sqlite:////data/books/calibre-webserver.db]
[I 240323 04:15:57 main:128] Init Static  with [/var/www/talebook/webserver/resources]
[I 240323 04:15:57 main:129] Init HTML    with [/var/www/talebook/webserver/../app/dist]
[I 240323 04:15:57 main:130] Init Nuxtjs  with [/var/www/talebook/webserver/../app/.env]
[I 240323 04:15:57 models:41] Bind modles._session()
[I 240323 04:16:00 main:193] Now, Running...
[D 240323 04:16:01 selector_events:59] Using selector: EpollSelector
[D 240323 04:16:07 base:218] Query User(1) = <id=1, username=admin, email=XXX@qq.com>
[I 240323 04:16:07 web:2239] 200 GET /api/user/info?detail=1 (172.17.0.1) 152.50ms
[D 240323 04:16:07 base:218] Query User(1) = <id=1, username=admin, email=XXX@qq.com>
[I 240323 04:16:07 web:2239] 304 GET /api/user/info?detail=1 (172.17.0.1) 37.94ms
[D 240323 04:16:15 base:218] Query User(1) = <id=1, username=admin, email=XXX@qq.com>
[D 240323 04:16:15 admin:36] num=10, page=0, sort=access_time, desc=true
[I 240323 04:16:15 web:2239] 304 GET /api/admin/users?page=1&sort=access_time&desc=true&num=10 (172.17.0.1) 43.78ms
[D 240323 04:16:15 base:218] Query User(1) = <id=1, username=admin, email=XXX@qq.com>
[D 240323 04:16:15 admin:36] num=10, page=0, sort=access_time, desc=true
[I 240323 04:16:15 web:2239] 304 GET /api/admin/users?page=1&sort=access_time&desc=true&num=10 (172.17.0.1) 7.61ms
[D 240323 04:16:16 base:218] Query User(1) = <id=1, username=admin, email=XXX@qq.com>
[I 240323 04:16:16 web:2239] 200 GET /api/admin/settings (172.17.0.1) 4.89ms
[D 240323 04:16:27 base:218] Query User(1) = <id=1, username=admin, email=XXX@qq.com>
[E 240323 04:16:27 loader:72] saving settings file: /data/books/settings/auto.py
[I 240323 04:16:27 web:2239] 200 POST /api/admin/settings (172.17.0.1) 49.50ms
[I 240323 04:16:27 autoreload:201] /data/books/settings/auto.py modified; restarting server
[I 240323 04:16:28 main:126] Init library with [/data/books/library]
[I 240323 04:16:28 main:127] Init AuthDB  with [sqlite:////data/books/calibre-webserver.db]
[I 240323 04:16:28 main:128] Init Static  with [/var/www/talebook/webserver/resources]
[I 240323 04:16:28 main:129] Init HTML    with [/var/www/talebook/webserver/../app/dist]
[I 240323 04:16:28 main:130] Init Nuxtjs  with [/var/www/talebook/webserver/../app/.env]
[I 240323 04:16:28 models:41] Bind modles._session()
[I 240323 04:16:28 main:193] Now, Running...
[D 240323 04:16:28 selector_events:59] Using selector: EpollSelector`

# 书籍文件
如果是特定某本书出现异常，请上传该书籍文件

# 其他
如果是比较复杂的问题，可以把整个书库 `/books/library/metadata.db` 数据库文件上传，以便作者复现异常场景

**Comment by Huster1993** [comment]
[metadata.db.zip](https://github.com/talebook/talebook/files/14730279/metadata.db.zip)

**Comment by talebook** [comment]
lxml.etree._utf8 ValueError: All strings must be XML compatible: Unicode or ASCII, no NULL bytes or control characters
----
名称有特殊字符导致的。我后面加些处理
