### ISSUE TITLE
从互联网同步书籍信息出现异常

### ISSUE THREAD

**Issue by victorwoo** [talebook/talebook#387]
# 问题描述
从互联网同步书籍信息出现异常。

# 问题环境
- 版本号：例如v3.8.0
- URL：http://home.vichamp.com:8880/ 缺省用户密码还没改，可以登进去看。
- 运行系统：群晖 DS1821+，DSM 7.2.1-69057 Update 3
- 访问设备：Mac + Edge 浏览器
- 浏览器版本：Edge 123.0.2420.81
- 书籍信息：《未来简史》[以色列]尤瓦尔·赫拉利著，2016年版

# 复现步骤
1. 在群晖的 Container Manager 中安装 eallion/douban-api-rs 并正常启动它。因为群晖的 docker 注册表中无法搜到 ghcr.io/cxfksword/douban-api-rs
2. 配置豆瓣插件地址：http://eallion-douban-api-rs-1
3. 打开一本电子书《未来简史》，从互联网同步书籍信息，能够正常显示出从豆瓣获取的信息。点击“设置”后，无论是设置书籍信息还是图片，都弹出 Exception 对话框
![WX20240408-183346](https://github.com/talebook/talebook/assets/173351/f5d82075-3159-4b2d-a18b-14ef2548d529)

# 截图
请上传报错的截图

# 报错信息
```
Exception:
Traceback (most recent call last):
  File "/var/www/talebook/webserver/handlers/base.py", line 49, in do
    rsp = func(self, *args, **kwargs)
  File "/var/www/talebook/webserver/handlers/base.py", line 76, in do
    return func(self, *args, **kwargs)
  File "/var/www/talebook/webserver/handlers/book.py", line 196, in post
    if len(refer_mi.tags) == 0 and len(mi.tags) == 0:
AttributeError: 'dict' object has no attribute 'tags'
```

# 日志
[talebook.log](https://github.com/talebook/talebook/files/14904331/talebook.log)

# 书籍文件
[《未来简史》作者：[以色列]尤瓦尔·赫拉利_中文版.epub.zip](https://github.com/talebook/talebook/files/14904333/_.epub.zip)

# 其他
如果是比较复杂的问题，可以把整个书库 `/books/library/metadata.db` 数据库文件上传，以便作者复现异常场景

**Comment by victorwoo** [comment]
解决了，应该是 docker 镜像的问题，不能用 eallion/douban-api-rs，得用 ghcr.io/cxfksword/douban-api-rs
