### ISSUE TITLE
服务器正在启动中...

### ISSUE THREAD

**Issue by blackedxyz** [talebook/talebook#416]
# 问题描述
服务器正在启动中...

# 问题环境
- 版本号：talebook/talebook                  latest    fb0fa9c485c3   3 weeks ago     2.18GB

- URL：[出现异常时的URL](http://192.168.50.89:8080/)
- 运行系统：NAS上的DOCKER
- 访问设备：Windows10 x64
- 浏览器版本：版本 5.1.1130.128（正式版本） （64 位） (Chromium 118.0.5993.159)
- 书籍信息：如果是特定的书异常，请提供「书名」和「作者名」

# 复现步骤
1. 先做啥
2. 再做啥
3. 看到报错XXX

docker run -d --name talebook -p 8080:80 -v /volume1/Obsidian:/data talebook/talebook

# 截图
请上传报错的截图
![2024-6-26 12-35-10](https://github.com/talebook/talebook/assets/71172897/2fd7bc45-7ec9-4a67-b869-6607e3d3bd6a)

# 报错信息
root@DSM7:~# docker logs d4dd3464113f
updating '/data/' permission to 1000:1000
ERROR:root:Traceback (most recent call last):
  File "/var/www/talebook/webserver/loader.py", line 40, in loadfile
    import auto
ModuleNotFoundError: No module named 'auto'

INFO:root:Init library with [/data/books/library/]
INFO:root:Init AuthDB  with [sqlite:////data/books/calibre-webserver.db]
INFO:root:Init Static  with [/var/www/talebook/webserver/resources]
INFO:root:Init HTML    with [/var/www/talebook/webserver/../app/dist]
INFO:root:Init Nuxtjs  with [/var/www/talebook/webserver/../app/.env]
INFO:root:Bind modles._session()
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/base.py", line 146, in __init__
    self._dbapi_connection = engine.raw_connection()
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/base.py", line 3300, in raw_connection
    return self.pool.connect()
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/pool/base.py", line 449, in connect
    return _ConnectionFairy._checkout(self)
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/pool/base.py", line 1263, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/pool/base.py", line 712, in checkout
    rec = pool._do_get()
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/pool/impl.py", line 180, in _do_get
    self._dec_overflow()
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/pool/impl.py", line 177, in _do_get
    return self._create_connection()
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/pool/base.py", line 390, in _create_connection
    return _ConnectionRecord(self)
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/pool/base.py", line 674, in __init__
    self.__connect()
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/pool/base.py", line 901, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/pool/base.py", line 896, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/create.py", line 643, in connect
    return dialect.connect(*cargs, **cparams)
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/default.py", line 620, in connect
    return self.loaded_dbapi.connect(*cargs, **cparams)
sqlite3.OperationalError: unable to open database file

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/www/talebook/server.py", line 13, in <module>
    sys.exit(webserver.main.main())
  File "/var/www/talebook/webserver/main.py", line 219, in main
    app = make_app()
  File "/var/www/talebook/webserver/main.py", line 149, in make_app
    models.user_syncdb(engine)
  File "/var/www/talebook/webserver/models.py", line 315, in user_syncdb
    Base.metadata.create_all(engine)
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/sql/schema.py", line 5857, in create_all
    bind._run_ddl_visitor(
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/base.py", line 3250, in _run_ddl_visitor
    with self.begin() as conn:
  File "/usr/lib/python3.9/contextlib.py", line 117, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/base.py", line 3240, in begin
    with self.connect() as conn:
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/base.py", line 3276, in connect
    return self._connection_cls(self)
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/base.py", line 148, in __init__
    Connection._handle_dbapi_exception_noconnection(
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/base.py", line 2440, in _handle_dbapi_exception_noconnection
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/base.py", line 146, in __init__
    self._dbapi_connection = engine.raw_connection()
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/base.py", line 3300, in raw_connection
    return self.pool.connect()
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/pool/base.py", line 449, in connect
    return _ConnectionFairy._checkout(self)
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/pool/base.py", line 1263, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/pool/base.py", line 712, in checkout
    rec = pool._do_get()
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/pool/impl.py", line 180, in _do_get
    self._dec_overflow()
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/pool/impl.py", line 177, in _do_get
    return self._create_connection()
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/pool/base.py", line 390, in _create_connection
    return _ConnectionRecord(self)
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/pool/base.py", line 674, in __init__
    self.__connect()
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/pool/base.py", line 901, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/pool/base.py", line 896, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/create.py", line 643, in connect
    return dialect.connect(*cargs, **cparams)
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/default.py", line 620, in connect
    return self.loaded_dbapi.connect(*cargs, **cparams)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) unable to open database file
(Background on this error at: https://sqlalche.me/e/20/e3q8)
ERROR:root:Traceback (most recent call last):
  File "/var/www/talebook/webserver/loader.py", line 40, in loadfile
    import auto
ModuleNotFoundError: No module named 'auto'

INFO:root:Init library with [/data/books/library/]
INFO:root:Init AuthDB  with [sqlite:////data/books/calibre-webserver.db]
INFO:root:Init Static  with [/var/www/talebook/webserver/resources]
INFO:root:Init HTML    with [/var/www/talebook/webserver/../app/dist]
INFO:root:Init Nuxtjs  with [/var/www/talebook/webserver/../app/.env]
INFO:root:updating configs ...
ERROR:root:service register <auto_fill_all>
ERROR:root:service register <auto_fill>
ERROR:root:service register <send_mail>
ERROR:root:service register <send_book>
INFO:root:done
Restarting nginx: nginx.
2024-06-26 12:24:59,903 INFO Included extra file "/etc/supervisor/conf.d/talebook.conf" during parsing
2024-06-26 12:24:59,903 INFO Set uid to user 0 succeeded
2024-06-26 12:24:59,933 INFO RPC interface 'supervisor' initialized
2024-06-26 12:24:59,933 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2024-06-26 12:24:59,934 INFO supervisord started with pid 1
2024-06-26 12:25:00,937 INFO spawned: 'tornado' with pid 61
2024-06-26 12:25:02,295 INFO success: tornado entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2024-06-26 12:25:05,403 INFO exited: tornado (exit status 1; not expected)
2024-06-26 12:25:06,404 INFO spawned: 'tornado' with pid 68
2024-06-26 12:25:07,157 INFO exited: tornado (exit status 1; not expected)
2024-06-26 12:25:08,160 INFO spawned: 'tornado' with pid 75
2024-06-26 12:25:09,144 INFO exited: tornado (exit status 1; not expected)
2024-06-26 12:25:11,148 INFO spawned: 'tornado' with pid 82
2024-06-26 12:25:11,868 INFO exited: tornado (exit status 1; not expected)
2024-06-26 12:25:14,872 INFO spawned: 'tornado' with pid 89
2024-06-26 12:25:15,549 INFO exited: tornado (exit status 1; not expected)
2024-06-26 12:25:16,551 INFO gave up: tornado entered FATAL state, too many start retries too quickly
2024-06-26 12:27:21,670 WARN received SIGTERM indicating exit request
usermod: no changes
ERROR:root:Traceback (most recent call last):
  File "/var/www/talebook/webserver/loader.py", line 40, in loadfile
    import auto
ModuleNotFoundError: No module named 'auto'

INFO:root:Init library with [/data/books/library/]
INFO:root:Init AuthDB  with [sqlite:////data/books/calibre-webserver.db]
INFO:root:Init Static  with [/var/www/talebook/webserver/resources]
INFO:root:Init HTML    with [/var/www/talebook/webserver/../app/dist]
INFO:root:Init Nuxtjs  with [/var/www/talebook/webserver/../app/.env]
INFO:root:Bind modles._session()
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/base.py", line 146, in __init__
    self._dbapi_connection = engine.raw_connection()
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/base.py", line 3300, in raw_connection
    return self.pool.connect()
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/pool/base.py", line 449, in connect
    return _ConnectionFairy._checkout(self)
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/pool/base.py", line 1263, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/pool/base.py", line 712, in checkout
    rec = pool._do_get()
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/pool/impl.py", line 180, in _do_get
    self._dec_overflow()
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/pool/impl.py", line 177, in _do_get
    return self._create_connection()
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/pool/base.py", line 390, in _create_connection
    return _ConnectionRecord(self)
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/pool/base.py", line 674, in __init__
    self.__connect()
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/pool/base.py", line 901, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/pool/base.py", line 896, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/create.py", line 643, in connect
    return dialect.connect(*cargs, **cparams)
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/default.py", line 620, in connect
    return self.loaded_dbapi.connect(*cargs, **cparams)
sqlite3.OperationalError: unable to open database file

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/www/talebook/server.py", line 13, in <module>
    sys.exit(webserver.main.main())
  File "/var/www/talebook/webserver/main.py", line 219, in main
    app = make_app()
  File "/var/www/talebook/webserver/main.py", line 149, in make_app
    models.user_syncdb(engine)
  File "/var/www/talebook/webserver/models.py", line 315, in user_syncdb
    Base.metadata.create_all(engine)
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/sql/schema.py", line 5857, in create_all
    bind._run_ddl_visitor(
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/base.py", line 3250, in _run_ddl_visitor
    with self.begin() as conn:
  File "/usr/lib/python3.9/contextlib.py", line 117, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/base.py", line 3240, in begin
    with self.connect() as conn:
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/base.py", line 3276, in connect
    return self._connection_cls(self)
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/base.py", line 148, in __init__
    Connection._handle_dbapi_exception_noconnection(
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/base.py", line 2440, in _handle_dbapi_exception_noconnection
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/base.py", line 146, in __init__
    self._dbapi_connection = engine.raw_connection()
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/base.py", line 3300, in raw_connection
    return self.pool.connect()
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/pool/base.py", line 449, in connect
    return _ConnectionFairy._checkout(self)
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/pool/base.py", line 1263, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/pool/base.py", line 712, in checkout
    rec = pool._do_get()
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/pool/impl.py", line 180, in _do_get
    self._dec_overflow()
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/pool/impl.py", line 177, in _do_get
    return self._create_connection()
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/pool/base.py", line 390, in _create_connection
    return _ConnectionRecord(self)
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/pool/base.py", line 674, in __init__
    self.__connect()
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/pool/base.py", line 901, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/pool/base.py", line 896, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/create.py", line 643, in connect
    return dialect.connect(*cargs, **cparams)
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/default.py", line 620, in connect
    return self.loaded_dbapi.connect(*cargs, **cparams)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) unable to open database file
(Background on this error at: https://sqlalche.me/e/20/e3q8)
ERROR:root:Traceback (most recent call last):
  File "/var/www/talebook/webserver/loader.py", line 40, in loadfile
    import auto
ModuleNotFoundError: No module named 'auto'

INFO:root:Init library with [/data/books/library/]
INFO:root:Init AuthDB  with [sqlite:////data/books/calibre-webserver.db]
INFO:root:Init Static  with [/var/www/talebook/webserver/resources]
INFO:root:Init HTML    with [/var/www/talebook/webserver/../app/dist]
INFO:root:Init Nuxtjs  with [/var/www/talebook/webserver/../app/.env]
INFO:root:updating configs ...
ERROR:root:service register <auto_fill_all>
ERROR:root:service register <auto_fill>
ERROR:root:service register <send_mail>
ERROR:root:service register <send_book>
INFO:root:done
Restarting nginx: nginx.
2024-06-26 12:27:36,049 INFO Included extra file "/etc/supervisor/conf.d/talebook.conf" during parsing
2024-06-26 12:27:36,049 INFO Set uid to user 0 succeeded
2024-06-26 12:27:36,060 INFO RPC interface 'supervisor' initialized
2024-06-26 12:27:36,060 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2024-06-26 12:27:36,061 INFO supervisord started with pid 1
2024-06-26 12:27:37,064 INFO spawned: 'tornado' with pid 52
2024-06-26 12:27:37,982 INFO exited: tornado (exit status 1; not expected)
2024-06-26 12:27:38,985 INFO spawned: 'tornado' with pid 60
2024-06-26 12:27:39,678 INFO exited: tornado (exit status 1; not expected)
2024-06-26 12:27:41,683 INFO spawned: 'tornado' with pid 67
2024-06-26 12:27:42,331 INFO exited: tornado (exit status 1; not expected)
2024-06-26 12:27:45,337 INFO spawned: 'tornado' with pid 74
2024-06-26 12:27:46,045 INFO exited: tornado (exit status 1; not expected)
2024-06-26 12:27:47,046 INFO gave up: tornado entered FATAL state, too many start retries too quickly
root@DSM7:~#

# 日志
请上传 `talebook.log` 文件，或截取日志中 提示 `Exceptions` 的部分

# 书籍文件
如果是特定某本书出现异常，请上传该书籍文件

# 其他
如果是比较复杂的问题，可以把整个书库 `/books/library/metadata.db` 数据库文件上传，以便作者复现异常场景

**Comment by talebook** [comment]
你这个问题，看起来是挂载的目录中残留了之前的数据文件，但是又有缺失` /volume1/Obsidian/books/settings/auto.py`

**Comment by junxiaoyao** [comment]
我也是这个问题感觉是bug，因为我已经尝试删除挂载目录甚至清理了docker的目录

**Comment by junxiaoyao** [comment]
经过我不挂载目录发现正常，因此推测是目录权限问题，我是群晖，因此将挂载目录设置为everyone即可了，成功解决问题

**Comment by jeffry88** [comment]
我也是这个问题

**Comment by talebook** [comment]
> 经过我不挂载目录发现正常，因此推测是目录权限问题，我是群晖，因此将挂载目录设置为everyone即可了，成功解决问题

挂载权限问题。
