### ISSUE TITLE
从豆瓣更新图书信息，图片处理异常

### ISSUE THREAD

**Issue by roadinger** [talebook/talebook#432]
从互联网更新信息，图片处理异常，信息来源：豆瓣

异常信息：
Exception:
Traceback (most recent call last):
  File "/var/www/talebook/webserver/handlers/base.py", line 49, in do
    rsp = func(self, *args, **kwargs)
  File "/var/www/talebook/webserver/handlers/base.py", line 76, in do
    return func(self, *args, **kwargs)
  File "/var/www/talebook/webserver/handlers/book.py", line 209, in post
    self.db.set_metadata(book_id, mi)
  File "/usr/lib/calibre/calibre/db/legacy.py", line 581, in set_metadata
    self.new_api.set_metadata(book_id, mi, ignore_errors=ignore_errors, set_title=set_title, set_authors=set_authors, force_changes=force_changes)
  File "/usr/lib/calibre/calibre/db/cache.py", line 72, in call_func_with_lock
    return func(*args, **kwargs)
  File "/usr/lib/calibre/calibre/db/cache.py", line 1414, in set_metadata
    self._set_cover({book_id: cdata})
  File "/usr/lib/calibre/calibre/db/cache.py", line 1337, in set_cover
    self.backend.set_cover(book_id, path, data)
  File "/usr/lib/calibre/calibre/db/backend.py", line 1515, in set_cover
    save_cover_data_to(data, path)
  File "/usr/lib/calibre/calibre/utils/img.py", line 289, in save_cover_data_to
    f.write(image_to_data(img, compression_quality, fmt, compression_quality // 10) if changed else data)
  File "/usr/lib/calibre/calibre/utils/img.py", line 197, in image_to_data
    raise ValueError('Failed to export image as ' + fmt + ' with error: ' + w.errorString())
ValueError: Failed to export image as JPEG with error: Image is empty

**Comment by roadinger** [comment]
任何书籍都报错，封面图处理有问题，比如：鸟哥的Linux私房菜—基础学习篇（第四版）
![1](https://github.com/user-attachments/assets/5813904b-4880-4171-acb2-2b3fc3f2cbc1)
![2](https://github.com/user-attachments/assets/a9785249-1af9-44ef-9d37-d8ca716ec1d9)
![Uploading 3.png…]()

**Comment by roadinger** [comment]
![Uploading 3.png…]()

**Comment by roadinger** [comment]
仅设置书籍信息没问题

**Comment by talebook** [comment]
你的豆瓣api用的是什么镜像的？我自己用 `ghcr.io/cxfksword/douban-api-rs` 测试是正常的。这个报错就是没拉取到图片的内容，需要看看具体的响应包是啥，光看截图没法debug

**Comment by roadinger** [comment]
eallion/douban-api-rs  这个镜像

**Comment by roadinger** [comment]
试了下  你这个镜像可以
