### ISSUE TITLE
docker镜像运行报错

### ISSUE THREAD

**Issue by bigcat26** [talebook/talebook#434]
# 问题描述
启动python报找不到auto，后面tornado无限重启。data文件夹已建立，所有者为1000:1000。

# 问题环境
- 运行系统：synology dsm 7.1

# 复现步骤
直接用docker-compose运行:

```yml
version: '3'

services:
  talebook:
    container_name: talebook
    image: talebook/talebook:latest
    volumes:
      - ./data:/data
    ports:
      - "0.0.0.0:5800:80"
    restart: unless-stopped
```

# 报错信息
```
talebook    | usermod: no changes
talebook    | ERROR:root:Traceback (most recent call last):
talebook    |   File "/var/www/talebook/webserver/loader.py", line 40, in loadfile
talebook    |     import auto
talebook    | ModuleNotFoundError: No module named 'auto'
talebook    |
talebook    | INFO:root:Init library with [/data/books/library/]
talebook    | INFO:root:Init AuthDB  with [sqlite:////data/books/calibre-webserver.db]
talebook    | INFO:root:Init Static  with [/var/www/talebook/webserver/resources]
talebook    | INFO:root:Init HTML    with [/var/www/talebook/webserver/../app/dist]
talebook    | INFO:root:Init Nuxtjs  with [/var/www/talebook/webserver/../app/.env]
talebook    | INFO:root:Bind modles._session()
talebook    | Traceback (most recent call last):
talebook    |   File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/base.py", line 146, in __init__
talebook    |     self._dbapi_connection = engine.raw_connection()
talebook    |   File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/base.py", line 3300, in raw_connection
talebook    |     return self.pool.connect()
talebook    |   File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/pool/base.py", line 449, in connect
talebook    |     return _ConnectionFairy._checkout(self)
talebook    |   File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/pool/base.py", line 1263, in _checkout
talebook    |     fairy = _ConnectionRecord.checkout(pool)
talebook    |   File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/pool/base.py", line 712, in checkout
talebook    |     rec = pool._do_get()
talebook    |   File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/pool/impl.py", line 180, in _do_get
talebook    |     self._dec_overflow()
talebook    |   File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
talebook    |     raise exc_value.with_traceback(exc_tb)
talebook    |   File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/pool/impl.py", line 177, in _do_get
talebook    |     return self._create_connection()
talebook    |   File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/pool/base.py", line 390, in _create_connection
talebook    |     return _ConnectionRecord(self)
talebook    |   File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/pool/base.py", line 674, in __init__
talebook    |     self.__connect()
talebook    |   File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/pool/base.py", line 901, in __connect
talebook    |     pool.logger.debug("Error on connect(): %s", e)
talebook    |   File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
talebook    |     raise exc_value.with_traceback(exc_tb)
talebook    |   File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/pool/base.py", line 896, in __connect
talebook    |     self.dbapi_connection = connection = pool._invoke_creator(self)
talebook    |   File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/create.py", line 643, in connect
talebook    |     return dialect.connect(*cargs, **cparams)
talebook    |   File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/default.py", line 620, in connect
talebook    |     return self.loaded_dbapi.connect(*cargs, **cparams)
talebook    | sqlite3.OperationalError: unable to open database file
talebook    |
talebook    | The above exception was the direct cause of the following exception:
talebook    |
talebook    | Traceback (most recent call last):
talebook    |   File "/var/www/talebook/server.py", line 13, in <module>
talebook    |     sys.exit(webserver.main.main())
talebook    |   File "/var/www/talebook/webserver/main.py", line 219, in main
talebook    |     app = make_app()
talebook    |   File "/var/www/talebook/webserver/main.py", line 149, in make_app
talebook    |     models.user_syncdb(engine)
talebook    |   File "/var/www/talebook/webserver/models.py", line 315, in user_syncdb
talebook    |     Base.metadata.create_all(engine)
talebook    |   File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/sql/schema.py", line 5857, in create_all
talebook    |     bind._run_ddl_visitor(
talebook    |   File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/base.py", line 3250, in _run_ddl_visitor
talebook    |     with self.begin() as conn:
talebook    |   File "/usr/lib/python3.9/contextlib.py", line 117, in __enter__
talebook    |     return next(self.gen)
talebook    |   File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/base.py", line 3240, in begin
talebook    |     with self.connect() as conn:
talebook    |   File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/base.py", line 3276, in connect
talebook    |     return self._connection_cls(self)
talebook    |   File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/base.py", line 148, in __init__
talebook    |     Connection._handle_dbapi_exception_noconnection(
talebook    |   File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/base.py", line 2440, in _handle_dbapi_exception_noconnection
talebook    |     raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
talebook    |   File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/base.py", line 146, in __init__
talebook    |     self._dbapi_connection = engine.raw_connection()
talebook    |   File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/base.py", line 3300, in raw_connection
talebook    |     return self.pool.connect()
talebook    |   File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/pool/base.py", line 449, in connect
talebook    |     return _ConnectionFairy._checkout(self)
talebook    |   File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/pool/base.py", line 1263, in _checkout
talebook    |     fairy = _ConnectionRecord.checkout(pool)
talebook    |   File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/pool/base.py", line 712, in checkout
talebook    |     rec = pool._do_get()
talebook    |   File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/pool/impl.py", line 180, in _do_get
talebook    |     self._dec_overflow()
talebook    |   File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
talebook    |     raise exc_value.with_traceback(exc_tb)
talebook    |   File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/pool/impl.py", line 177, in _do_get
talebook    |     return self._create_connection()
talebook    |   File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/pool/base.py", line 390, in _create_connection
talebook    |     return _ConnectionRecord(self)
talebook    |   File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/pool/base.py", line 674, in __init__
talebook    |     self.__connect()
talebook    |   File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/pool/base.py", line 901, in __connect
talebook    |     pool.logger.debug("Error on connect(): %s", e)
talebook    |   File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
talebook    |     raise exc_value.with_traceback(exc_tb)
talebook    |   File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/pool/base.py", line 896, in __connect
talebook    |     self.dbapi_connection = connection = pool._invoke_creator(self)
talebook    |   File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/create.py", line 643, in connect
talebook    |     return dialect.connect(*cargs, **cparams)
talebook    |   File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/default.py", line 620, in connect
talebook    |     return self.loaded_dbapi.connect(*cargs, **cparams)
talebook    | sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) unable to open database file
talebook    | (Background on this error at: https://sqlalche.me/e/20/e3q8)
talebook    | ERROR:root:Traceback (most recent call last):
talebook    |   File "/var/www/talebook/webserver/loader.py", line 40, in loadfile
talebook    |     import auto
talebook    | ModuleNotFoundError: No module named 'auto'
talebook    |
talebook    | INFO:root:Init library with [/data/books/library/]
talebook    | INFO:root:Init AuthDB  with [sqlite:////data/books/calibre-webserver.db]
talebook    | INFO:root:Init Static  with [/var/www/talebook/webserver/resources]
talebook    | INFO:root:Init HTML    with [/var/www/talebook/webserver/../app/dist]
talebook    | INFO:root:Init Nuxtjs  with [/var/www/talebook/webserver/../app/.env]
talebook    | INFO:root:updating configs ...
talebook    | ERROR:root:service register <auto_fill_all>
talebook    | ERROR:root:service register <auto_fill>
talebook    | ERROR:root:service register <send_mail>
talebook    | ERROR:root:service register <send_book>
talebook    | INFO:root:done
talebook    | Restarting nginx: nginx.
talebook    | 2024-10-14 15:07:09,082 INFO Included extra file "/etc/supervisor/conf.d/talebook.conf" during parsing
talebook    | 2024-10-14 15:07:09,082 INFO Set uid to user 0 succeeded
talebook    | 2024-10-14 15:07:09,090 INFO RPC interface 'supervisor' initialized
talebook    | 2024-10-14 15:07:09,090 CRIT Server 'unix_http_server' running without any HTTP authentication checking
talebook    | 2024-10-14 15:07:09,092 INFO supervisord started with pid 1
talebook    | 2024-10-14 15:07:10,095 INFO spawned: 'tornado' with pid 49
talebook    | 2024-10-14 15:07:12,084 INFO success: tornado entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
talebook    | 2024-10-14 15:07:13,698 INFO exited: tornado (exit status 1; not expected)
talebook    | 2024-10-14 15:07:14,703 INFO spawned: 'tornado' with pid 55
talebook    | 2024-10-14 15:07:15,700 INFO success: tornado entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
talebook    | 2024-10-14 15:07:17,104 INFO exited: tornado (exit status 1; not expected)
talebook    | 2024-10-14 15:07:18,108 INFO spawned: 'tornado' with pid 62
talebook    | 2024-10-14 15:07:19,644 INFO success: tornado entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
talebook    | 2024-10-14 15:07:19,933 INFO exited: tornado (exit status 1; not expected)
talebook    | 2024-10-14 15:07:20,937 INFO spawned: 'tornado' with pid 68
talebook    | 2024-10-14 15:07:22,436 INFO success: tornado entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
talebook    | 2024-10-14 15:07:23,514 INFO exited: tornado (exit status 1; not expected)
```

**Comment by talebook** [comment]
这种情况是对data目录做初始化时失败了，文件无法创建。可以再检查一下权限，在docker-compose中明确设置一下UID/GID：
```
    environment:
      - PUID=1000
      - PGID=1000
```

**Comment by bigcat26** [comment]
加了无用。文件有创建成功：

```bash
$ sudo ls -la data/
total 4
d---------+ 1  1000  1000  38 Oct 14 14:58 .
d---------+ 1 chris users  44 Oct 15 14:36 ..
d---------  1  1000  1000 154 Oct 14 14:58 books
d---------  1  1000  1000  34 Oct 14 14:58 log
----------+ 1  1000  1000  10 Oct 15 14:37 .permission

$ sudo ls -la data/books/

total 72
d---------  1 1000 1000   154 Oct 14 14:58 .
d---------+ 1 1000 1000    38 Oct 14 14:58 ..
-rw-r--r--  1 1000 1000 73728 Oct 14 14:58 calibre-webserver.db
drwxr-xr-x  1 1000 1000     0 Oct 14 14:58 convert
drwxr-xr-x  1 1000 1000     0 Oct 14 14:58 extract
drwxr-xr-x  1 1000 1000     0 Oct 14 14:58 imports
drwxr-xr-x  1 1000 1000    58 Oct 14 14:58 library
drwxr-xr-x  1 1000 1000    38 Oct 14 14:58 logo
drwxr-xr-x  1 1000 1000     0 Oct 14 14:58 progress
drwxr-xr-x  1 1000 1000    36 Oct 14 14:58 settings
drwxr-xr-x  1 1000 1000    28 Oct 14 14:58 ssl
drwxr-xr-x  1 1000 1000     0 Oct 14 14:58 upload

$ sudo sqlite3 data/books/calibre-webserver.db
SQLite version 3.34.1 2021-01-20 14:10:07
Enter ".help" for usage hints.
sqlite> .schema;
Error: unknown command or invalid arguments:  "schema;". Enter ".help" for help
sqlite> .schema
CREATE TABLE readers (
	id INTEGER NOT NULL,
	username VARCHAR(200),
	password VARCHAR(200),
	salt VARCHAR(200),
	name VARCHAR(100),
	email VARCHAR(200),
	avatar VARCHAR(200),
	admin BOOLEAN,
	active BOOLEAN,
	permission VARCHAR(100),
	create_time DATETIME,
	update_time DATETIME,
	access_time DATETIME,
	extra TEXT,
	PRIMARY KEY (id)
);
CREATE TABLE scanfiles (
	id INTEGER NOT NULL,
	scan_id INTEGER,
	import_id INTEGER,
	name VARCHAR(512),
	path VARCHAR(1024),
	hash VARCHAR(512),
	status VARCHAR(24),
	title VARCHAR(100),
	author VARCHAR(100),
	publisher VARCHAR(100),
	tags VARCHAR(100),
	create_time DATETIME,
	update_time DATETIME,
	book_id INTEGER,
	data TEXT,
	PRIMARY KEY (id),
	UNIQUE (hash)
);
CREATE TABLE social_auth_nonce (
	id INTEGER NOT NULL,
	server_url VARCHAR(255),
	timestamp INTEGER,
	salt VARCHAR(40),
	PRIMARY KEY (id),
	UNIQUE (server_url, timestamp, salt)
);
CREATE TABLE social_auth_association (
	id INTEGER NOT NULL,
	server_url VARCHAR(255),
	handle VARCHAR(255),
	secret VARCHAR(255),
	issued INTEGER,
	lifetime INTEGER,
	assoc_type VARCHAR(64),
	PRIMARY KEY (id),
	UNIQUE (server_url, handle)
);
CREATE TABLE social_auth_code (
	id INTEGER NOT NULL,
	email VARCHAR(200),
	code VARCHAR(32),
	PRIMARY KEY (id),
	UNIQUE (code, email)
);
CREATE INDEX ix_social_auth_code_code ON social_auth_code (code);
CREATE TABLE social_auth_partial (
	id INTEGER NOT NULL,
	token VARCHAR(32),
	data TEXT,
	next_step INTEGER,
	backend VARCHAR(32),
	PRIMARY KEY (id)
);
CREATE INDEX ix_social_auth_partial_token ON social_auth_partial (token);
CREATE TABLE messages (
	id INTEGER NOT NULL,
	title VARCHAR(200),
	status VARCHAR(100),
	unread BOOLEAN,
	create_time DATETIME,
	update_time DATETIME,
	data TEXT,
	reader_id INTEGER,
	PRIMARY KEY (id),
	FOREIGN KEY(reader_id) REFERENCES readers (id)
);
CREATE TABLE items (
	book_id INTEGER NOT NULL,
	count_guest INTEGER NOT NULL,
	count_visit INTEGER NOT NULL,
	count_download INTEGER NOT NULL,
	website VARCHAR(255) NOT NULL,
	collector_id INTEGER,
	PRIMARY KEY (book_id),
	FOREIGN KEY(collector_id) REFERENCES readers (id)
);
CREATE TABLE social_auth_usersocialauth (
	uid VARCHAR(255),
	user_id INTEGER NOT NULL,
	id INTEGER NOT NULL,
	provider VARCHAR(32),
	extra_data TEXT,
	PRIMARY KEY (id),
	UNIQUE (provider, uid),
	FOREIGN KEY(user_id) REFERENCES readers (id)
);
CREATE INDEX ix_social_auth_usersocialauth_user_id ON social_auth_usersocialauth (user_id);
```

还是报ModuleNotFoundError: No module named 'auto'，和sqlite3.OperationalError: unable to open database file

**Comment by bigcat26** [comment]
看到问题所在了，data目录的perm是000，chmod -R 755 data就ok了
