### ISSUE TITLE
从互联网更新书籍信息后，设置书籍信息及图片报错

### ISSUE THREAD

**Issue by drdongli** [talebook/talebook#452]
# 问题描述
从互联网更新书籍信息后，设置书籍信息及图片报错

# 问题环境
- 版本号：例如v3.8.2
- URL：[出现异常时的URL](http://192.168.2.130:9000/book/25)
- 运行系统：群晖/DOCKER
- 访问设备：Mac
- 浏览器版本：Chrome 
- 书籍信息：所有都不行

# 报错信息
Exception:
Traceback (most recent call last):
  File "/var/www/talebook/webserver/handlers/base.py", line 49, in do
    rsp = func(self, *args, **kwargs)
  File "/var/www/talebook/webserver/handlers/base.py", line 76, in do
    return func(self, *args, **kwargs)
  File "/var/www/talebook/webserver/handlers/book.py", line 196, in post
    if len(refer_mi.tags) == 0 and len(mi.tags) == 0:
AttributeError: 'dict' object has no attribute 'tags'

# 日志
Exception:
Traceback (most recent call last):
  File "/var/www/talebook/webserver/handlers/base.py", line 49, in do
    rsp = func(self, *args, **kwargs)
  File "/var/www/talebook/webserver/handlers/base.py", line 76, in do
    return func(self, *args, **kwargs)
  File "/var/www/talebook/webserver/handlers/book.py", line 196, in post
    if len(refer_mi.tags) == 0 and len(mi.tags) == 0:
AttributeError: 'dict' object has no attribute 'tags'

**Comment by drdongli** [comment]
问题已经解决

解决办法 用talebook/douban-api-rs
不要用 其他人的
