### ISSUE TITLE
重启NAS后，书籍库打开报错，还望提供解决办法

### ISSUE THREAD

**Issue by heiselangman** [talebook/talebook#453]
# 问题描述
几句话简要描述问题
问题内容为：当天在docker上部署完，使用都是正常，但是当晚关闭了docker，第二天启动该NAS后，打开书库就提示报错了

# 问题环境
- 版本号：v3.8.2
- URL：出现异常时的URL   本地部署
- 运行系统：windows11系统下使用的docker-desktop的NAS
- 访问设备：Windows系统下的edge\QQ浏览器
- 浏览器版本：QQ浏览器版本版本 13.2（6135）
- 书籍信息：重新打开书库地址就弹出报错，关闭报错，点击任意一本书都会报错

# 复现步骤
1. 先做啥：先重启了整个win-NAS系统，启动docker；
2. 再做啥：再进行了访问本地部署的书库IP地址+端口号；
3. 看到报错XXX：Traceback (most recent call last):..........AttributeError: 'NoneType' object has no attribute 'isdigit'

# 截图
请上传报错的截图
![问题](https://github.com/user-attachments/assets/0879f8a9-cc8e-451a-bf58-5e7ab921b08b)

# 报错信息
把系统上提示的报错信息文字版粘贴出来：
Exception:
Traceback (most recent call last):
  File "/var/www/talebook/webserver/handlers/base.py", line 49, in do
    rsp = func(self, *args, **kwargs)
  File "/var/www/talebook/webserver/handlers/user.py", line 240, in get
    user = self.current_user
  File "/usr/local/lib/python3.9/dist-packages/tornado/web.py", line 1424, in current_user
    self._current_user = self.get_current_user()
  File "/var/www/talebook/webserver/handlers/base.py", line 213, in get_current_user
    user_id = self.user_id()
  File "/var/www/talebook/webserver/handlers/base.py", line 210, in user_id
    return int(uid) if uid.isdigit() else None
AttributeError: 'NoneType' object has no attribute 'isdigit'

# 日志
请上传 `talebook.log` 文件，或截取日志中 提示 `Exceptions` 的部分

# 书籍文件
如果是特定某本书出现异常，请上传该书籍文件
打开所有图书都会出现报错，无法再现阅读等
打开书籍报错内容：Exception:
Traceback (most recent call last):
  File "/var/www/talebook/webserver/handlers/base.py", line 49, in do
    rsp = func(self, *args, **kwargs)
  File "/var/www/talebook/webserver/handlers/book.py", line 66, in get
    "book": utils.BookFormatter(self, book).format(with_files=True, with_perms=True),
  File "/var/www/talebook/webserver/utils.py", line 104, in format
    data.update(self.get_permissions())
  File "/var/www/talebook/webserver/utils.py", line 89, in get_permissions
    "is_owner": h.is_admin() or h.is_book_owner(self.book["id"], h.user_id()),
  File "/var/www/talebook/webserver/handlers/base.py", line 229, in is_admin
    if not self.current_user:
  File "/usr/local/lib/python3.9/dist-packages/tornado/web.py", line 1424, in current_user
    self._current_user = self.get_current_user()
  File "/var/www/talebook/webserver/handlers/base.py", line 213, in get_current_user
    user_id = self.user_id()
  File "/var/www/talebook/webserver/handlers/base.py", line 210, in user_id
    return int(uid) if uid.isdigit() else None
AttributeError: 'NoneType' object has no attribute 'isdigit'

# 其他
如果是比较复杂的问题，可以把整个书库 `/books/library/metadata.db` 数据库文件上传，以便作者复现异常场景
[metadata.zip](https://github.com/user-attachments/files/17694085/metadata.zip)

**Comment by heiselangman** [comment]
重新生成新的容器（再不删除原配置的情况下，故障依旧）。
以下是原来的日志文件内容：
[32m[I 241111 09:07:10 main:127](B[m Init library with [/data/books/library/]
[32m[I 241111 09:07:10 main:128](B[m Init AuthDB  with [sqlite:////data/books/calibre-webserver.db]
[32m[I 241111 09:07:10 main:129](B[m Init Static  with [/var/www/talebook/webserver/resources]
[32m[I 241111 09:07:10 main:130](B[m Init HTML    with [/var/www/talebook/webserver/../app/dist]
[32m[I 241111 09:07:10 main:131](B[m Init Nuxtjs  with [/var/www/talebook/webserver/../app/.env]
[32m[I 241111 09:07:10 models:40](B[m Bind modles._session()
[32m[I 241111 09:07:10 main:150](B[m Create tables into DB
[32m[I 241111 09:07:11 main:127](B[m Init library with [/data/books/library/]
[32m[I 241111 09:07:11 main:128](B[m Init AuthDB  with [sqlite:////data/books/calibre-webserver.db]
[32m[I 241111 09:07:11 main:129](B[m Init Static  with [/var/www/talebook/webserver/resources]
[32m[I 241111 09:07:11 main:130](B[m Init HTML    with [/var/www/talebook/webserver/../app/dist]
[32m[I 241111 09:07:11 main:131](B[m Init Nuxtjs  with [/var/www/talebook/webserver/../app/.env]
[32m[I 241111 09:07:11 main:134](B[m updating configs ...
[31m[E 241111 09:07:11 async_service:97](B[m service register <auto_fill_all>
[31m[E 241111 09:07:11 async_service:84](B[m service register <auto_fill>
[31m[E 241111 09:07:11 async_service:97](B[m service register <send_mail>
[31m[E 241111 09:07:11 async_service:97](B[m service register <send_book>
[32m[I 241111 09:07:11 main:139](B[m done
Restarting nginx: nginx.
2024-11-11 09:07:12,405 INFO Included extra file "/etc/supervisor/conf.d/talebook.conf" during parsing
2024-11-11 09:07:12,405 INFO Set uid to user 0 succeeded
2024-11-11 09:07:12,408 INFO RPC interface 'supervisor' initialized
2024-11-11 09:07:12,408 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2024-11-11 09:07:12,409 INFO supervisord started with pid 1
2024-11-11 09:07:13,416 INFO spawned: 'tornado' with pid 67
2024-11-11 09:07:15,268 INFO success: tornado entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)

**Comment by heiselangman** [comment]
用宿主机访问就正常了，但是远程WEB访问，故障依旧

**Comment by Cdexs** [comment]
同样问题，重启docker就登陆不了了！

**Comment by talebook** [comment]
试下清除浏览器缓存
