### ISSUE TITLE
无法反向代理

### ISSUE THREAD

**Issue by XLXXLXXLX** [talebook/talebook#456]
# 问题描述
无法使用frp反向代理
frps：
```
Nov 24 06:41:45 frps[732]: 2024-11-24 06:41:45.645 [W] [httputil/reverseproxy.go:472] do http proxy request [host: ***.***.***] error: EOF
```

# 问题环境
直接按照主页的docker-compose.yml方式运行的
- 运行系统：Ubuntu22.04、Docker等
- 访问设备：Linux

# 尝试错误排查
按照主页的docker-compose.yml方式运行
ssh到小主机上，进行错误排查：
```
$sudo ss -tulpn | grep 8080
tcp   LISTEN 0      4096                                          0.0.0.0:8080       0.0.0.0:*    users:(("docker-proxy",pid=1528860,fd=4))
tcp   LISTEN 0      4096                                             [::]:8080          [::]:*    users:(("docker-proxy",pid=1528867,fd=4))
$curl localhost:8080
curl: (56) Recv failure: Connection reset by peer
```
可见不是frp的问题，然后尝试进入容器内排查错误：
```
$docker exec -it 5880c28cadbb /bin/bash
root@5880c28cadbb:/# curl localhost:80
<!doctype html>
<html lang="en">

<head>
  <title>talebook | talebook</title><meta data-n-head="1" charset="utf-8"><meta data-n-head="1" name="format-detection" content="tele
（中间省略掉）
<script src="/_nuxt/71f9a1f.js"></script><script src="/_nuxt/e5918fd.js"></script><script src="/_nuxt/1b52687.js"></script><script src="/_nuxt/ede7b7d.js"></script></body>

</html>
可见，容器内部的应用没有问题，应该是我的docker网络的问题？
```

# 日志
talebook.log似乎没有什么特别的
```
cat /tmp/demo/log/talebook.log
[I 241124 14:30:30 main:127] Init library with [/data/books/library]
[I 241124 14:30:30 main:128] Init AuthDB  with [sqlite:////data/books/calibre-webserver.db]
[I 241124 14:30:30 main:129] Init Static  with [/var/www/talebook/webserver/resources]
[I 241124 14:30:30 main:130] Init HTML    with [/var/www/talebook/webserver/../app/dist]
[I 241124 14:30:30 main:131] Init Nuxtjs  with [/var/www/talebook/webserver/../app/.env]
[I 241124 14:30:30 models:40] Bind modles._session()
[I 241124 14:30:31 main:194] Now, Running...
[E 241124 14:30:31 async_service:97] service register <auto_fill_all>
[E 241124 14:30:31 async_service:84] service register <auto_fill>
[E 241124 14:30:31 async_service:97] service register <send_mail>
[E 241124 14:30:31 async_service:97] service register <send_book>
[E 241124 14:30:31 async_service:97] service register <convert_and_send>
[E 241124 14:30:31 async_service:97] service register <convert_and_save>
[E 241124 14:30:31 async_service:97] service register <parse_txt_content>
[E 241124 14:30:31 async_service:97] service register <do_scan>
[E 241124 14:30:31 async_service:97] service register <do_import>
[D 241124 14:30:31 selector_events:59] Using selector: EpollSelector
[I 241124 14:52:11 main:127] Init library with [/data/books/library]
[I 241124 14:52:11 main:128] Init AuthDB  with [sqlite:////data/books/calibre-webserver.db]
[I 241124 14:52:11 main:129] Init Static  with [/var/www/talebook/webserver/resources]
[I 241124 14:52:11 main:130] Init HTML    with [/var/www/talebook/webserver/../app/dist]
[I 241124 14:52:11 main:131] Init Nuxtjs  with [/var/www/talebook/webserver/../app/.env]
[I 241124 14:52:11 models:40] Bind modles._session()
[I 241124 14:52:12 main:194] Now, Running...
[E 241124 14:52:12 async_service:97] service register <auto_fill_all>
[E 241124 14:52:12 async_service:84] service register <auto_fill>
[E 241124 14:52:12 async_service:97] service register <send_mail>
[E 241124 14:52:12 async_service:97] service register <send_book>
[E 241124 14:52:12 async_service:97] service register <convert_and_send>
[E 241124 14:52:12 async_service:97] service register <convert_and_save>
[E 241124 14:52:12 async_service:97] service register <parse_txt_content>
[E 241124 14:52:12 async_service:97] service register <do_scan>
[E 241124 14:52:12 async_service:97] service register <do_import>
[D 241124 14:52:12 selector_events:59] Using selector: EpollSelector
[I 241124 15:10:08 main:127] Init library with [/data/books/library]
[I 241124 15:10:08 main:128] Init AuthDB  with [sqlite:////data/books/calibre-webserver.db]
[I 241124 15:10:08 main:129] Init Static  with [/var/www/talebook/webserver/resources]
[I 241124 15:10:08 main:130] Init HTML    with [/var/www/talebook/webserver/../app/dist]
[I 241124 15:10:08 main:131] Init Nuxtjs  with [/var/www/talebook/webserver/../app/.env]
[I 241124 15:10:08 models:40] Bind modles._session()
[I 241124 15:10:09 main:194] Now, Running...
[E 241124 15:10:09 async_service:97] service register <auto_fill_all>
[E 241124 15:10:09 async_service:84] service register <auto_fill>
[E 241124 15:10:09 async_service:97] service register <send_mail>
[E 241124 15:10:09 async_service:97] service register <send_book>
[E 241124 15:10:09 async_service:97] service register <convert_and_send>
[E 241124 15:10:09 async_service:97] service register <convert_and_save>
[E 241124 15:10:09 async_service:97] service register <parse_txt_content>
[E 241124 15:10:09 async_service:97] service register <do_scan>
[E 241124 15:10:09 async_service:97] service register <do_import>
[D 241124 15:10:09 selector_events:59] Using selector: EpollSelector
```
```
cat /tmp/demo/log/nginx/*
127.0.0.1 - - [24/Nov/2024:06:53:43 +0000] "GET / HTTP/1.1" 200 3062 "-" "curl/7.74.0"
127.0.0.1 - - [24/Nov/2024:06:58:59 +0000] "GET / HTTP/1.1" 200 3062 "-" "curl/7.74.0"
127.0.0.1 - - [24/Nov/2024:06:59:21 +0000] "GET / HTTP/1.1" 200 3062 "-" "curl/7.74.0"
127.0.0.1 - - [24/Nov/2024:06:59:37 +0000] "GET / HTTP/1.1" 200 3062 "-" "curl/7.74.0"
127.0.0.1 - - [24/Nov/2024:07:19:01 +0000] "GET / HTTP/1.1" 200 3062 "-" "curl/7.74.0"
```
nginx的log也只记录到了我在容器内部成功的curl

-----

我估计不是talebook的问题，而是我的docker的问题，但我对docker掌握度不高，到处搜也没搞定，所以来请教一下

**Comment by talebook** [comment]
抱歉，没有研究过 frps ，不清楚原因，或许可以试试 network=host 模式

**Comment by slyang40** [comment]
我也是出现类似的问题。通过内网地址比如：192.168.1.1:80可以正常访问，但是通过反代就出现 500 错误。
错误日志如下：
`[E 241129 15:58:56 web:1875] Uncaught exception GET /get/cover/16.jpg?t=1732864753 (x.x.x.x) "1 xxxxxx"
    HTTPServerRequest(protocol='http', host='books.xxx.cc', method='GET', uri='/get/cover/16.jpg?t=1732864753', version='HTTP/1.0', remote_ip='175.162.7.98')
    Traceback (most recent call last):
      File "/usr/local/lib/python3.9/dist-packages/tornado/web.py", line 1767, in _execute
        result = self.prepare()
      File "/var/www/talebook/webserver/handlers/base.py", line 183, in prepare
        self.process_auth_header()
      File "/var/www/talebook/webserver/handlers/base.py", line 147, in process_auth_header
        self.login_user(user)
      File "/var/www/talebook/webserver/handlers/base.py", line 253, in login_user
        user.save()
      File "/var/www/talebook/webserver/models.py", line 123, in save
        return super().save()
      File "/usr/local/lib/python3.9/dist-packages/social_sqlalchemy/storage.py", line 82, in save
        self._save_instance(self)
      File "/usr/local/lib/python3.9/dist-packages/social_sqlalchemy/storage.py", line 62, in _save_instance
        cls._session().add(instance)
      File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/scoping.py", line 378, in add
        return self._proxied.add(instance, _warn=_warn)
      File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/session.py", line 3477, in add
        self._save_or_update_state(state)
      File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/session.py", line 3501, in _save_or_update_state
        self._save_or_update_impl(state)
      File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/session.py", line 4202, in _save_or_update_impl
        self._update_impl(state)
      File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/session.py", line 4185, in _update_impl
        to_attach = self._before_attach(state, obj)
      File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/session.py", line 4276, in _before_attach
        raise sa_exc.InvalidRequestError(
    sqlalchemy.exc.InvalidRequestError: Object '<Reader at 0x7f607cfd81c0>' is already attached to session '13' (this is '18')`

**Comment by mapxn** [comment]
你其他通过frp穿透的服务可以正常使用吗？

**Comment by hehetoshang** [comment]
> # 问题描述
> 无法使用frp反向代理 frps：
> 
> ```
> Nov 24 06:41:45 frps[732]: 2024-11-24 06:41:45.645 [W] [httputil/reverseproxy.go:472] do http proxy request [host: ***.***.***] error: EOF
> ```
> 
> # 问题环境
> 直接按照主页的docker-compose.yml方式运行的
> 
> * 运行系统：Ubuntu22.04、Docker等
> * 访问设备：Linux
> 
> # 尝试错误排查
> 按照主页的docker-compose.yml方式运行 ssh到小主机上，进行错误排查：
> 
> ```
> $sudo ss -tulpn | grep 8080
> tcp   LISTEN 0      4096                                          0.0.0.0:8080       0.0.0.0:*    users:(("docker-proxy",pid=1528860,fd=4))
> tcp   LISTEN 0      4096                                             [::]:8080          [::]:*    users:(("docker-proxy",pid=1528867,fd=4))
> $curl localhost:8080
> curl: (56) Recv failure: Connection reset by peer
> ```
> 
> 可见不是frp的问题，然后尝试进入容器内排查错误：
> 
> ```
> $docker exec -it 5880c28cadbb /bin/bash
> root@5880c28cadbb:/# curl localhost:80
> <!doctype html>
> <html lang="en">
> 
> <head>
>   <title>talebook | talebook</title><meta data-n-head="1" charset="utf-8"><meta data-n-head="1" name="format-detection" content="tele
> （中间省略掉）
> <script src="/_nuxt/71f9a1f.js"></script><script src="/_nuxt/e5918fd.js"></script><script src="/_nuxt/1b52687.js"></script><script src="/_nuxt/ede7b7d.js"></script></body>
> 
> </html>
> 可见，容器内部的应用没有问题，应该是我的docker网络的问题？
> ```
> 
> # 日志
> talebook.log似乎没有什么特别的
> 
> ```
> cat /tmp/demo/log/talebook.log
> [I 241124 14:30:30 main:127] Init library with [/data/books/library]
> [I 241124 14:30:30 main:128] Init AuthDB  with [sqlite:////data/books/calibre-webserver.db]
> [I 241124 14:30:30 main:129] Init Static  with [/var/www/talebook/webserver/resources]
> [I 241124 14:30:30 main:130] Init HTML    with [/var/www/talebook/webserver/../app/dist]
> [I 241124 14:30:30 main:131] Init Nuxtjs  with [/var/www/talebook/webserver/../app/.env]
> [I 241124 14:30:30 models:40] Bind modles._session()
> [I 241124 14:30:31 main:194] Now, Running...
> [E 241124 14:30:31 async_service:97] service register <auto_fill_all>
> [E 241124 14:30:31 async_service:84] service register <auto_fill>
> [E 241124 14:30:31 async_service:97] service register <send_mail>
> [E 241124 14:30:31 async_service:97] service register <send_book>
> [E 241124 14:30:31 async_service:97] service register <convert_and_send>
> [E 241124 14:30:31 async_service:97] service register <convert_and_save>
> [E 241124 14:30:31 async_service:97] service register <parse_txt_content>
> [E 241124 14:30:31 async_service:97] service register <do_scan>
> [E 241124 14:30:31 async_service:97] service register <do_import>
> [D 241124 14:30:31 selector_events:59] Using selector: EpollSelector
> [I 241124 14:52:11 main:127] Init library with [/data/books/library]
> [I 241124 14:52:11 main:128] Init AuthDB  with [sqlite:////data/books/calibre-webserver.db]
> [I 241124 14:52:11 main:129] Init Static  with [/var/www/talebook/webserver/resources]
> [I 241124 14:52:11 main:130] Init HTML    with [/var/www/talebook/webserver/../app/dist]
> [I 241124 14:52:11 main:131] Init Nuxtjs  with [/var/www/talebook/webserver/../app/.env]
> [I 241124 14:52:11 models:40] Bind modles._session()
> [I 241124 14:52:12 main:194] Now, Running...
> [E 241124 14:52:12 async_service:97] service register <auto_fill_all>
> [E 241124 14:52:12 async_service:84] service register <auto_fill>
> [E 241124 14:52:12 async_service:97] service register <send_mail>
> [E 241124 14:52:12 async_service:97] service register <send_book>
> [E 241124 14:52:12 async_service:97] service register <convert_and_send>
> [E 241124 14:52:12 async_service:97] service register <convert_and_save>
> [E 241124 14:52:12 async_service:97] service register <parse_txt_content>
> [E 241124 14:52:12 async_service:97] service register <do_scan>
> [E 241124 14:52:12 async_service:97] service register <do_import>
> [D 241124 14:52:12 selector_events:59] Using selector: EpollSelector
> [I 241124 15:10:08 main:127] Init library with [/data/books/library]
> [I 241124 15:10:08 main:128] Init AuthDB  with [sqlite:////data/books/calibre-webserver.db]
> [I 241124 15:10:08 main:129] Init Static  with [/var/www/talebook/webserver/resources]
> [I 241124 15:10:08 main:130] Init HTML    with [/var/www/talebook/webserver/../app/dist]
> [I 241124 15:10:08 main:131] Init Nuxtjs  with [/var/www/talebook/webserver/../app/.env]
> [I 241124 15:10:08 models:40] Bind modles._session()
> [I 241124 15:10:09 main:194] Now, Running...
> [E 241124 15:10:09 async_service:97] service register <auto_fill_all>
> [E 241124 15:10:09 async_service:84] service register <auto_fill>
> [E 241124 15:10:09 async_service:97] service register <send_mail>
> [E 241124 15:10:09 async_service:97] service register <send_book>
> [E 241124 15:10:09 async_service:97] service register <convert_and_send>
> [E 241124 15:10:09 async_service:97] service register <convert_and_save>
> [E 241124 15:10:09 async_service:97] service register <parse_txt_content>
> [E 241124 15:10:09 async_service:97] service register <do_scan>
> [E 241124 15:10:09 async_service:97] service register <do_import>
> [D 241124 15:10:09 selector_events:59] Using selector: EpollSelector
> ```
> 
> ```
> cat /tmp/demo/log/nginx/*
> 127.0.0.1 - - [24/Nov/2024:06:53:43 +0000] "GET / HTTP/1.1" 200 3062 "-" "curl/7.74.0"
> 127.0.0.1 - - [24/Nov/2024:06:58:59 +0000] "GET / HTTP/1.1" 200 3062 "-" "curl/7.74.0"
> 127.0.0.1 - - [24/Nov/2024:06:59:21 +0000] "GET / HTTP/1.1" 200 3062 "-" "curl/7.74.0"
> 127.0.0.1 - - [24/Nov/2024:06:59:37 +0000] "GET / HTTP/1.1" 200 3062 "-" "curl/7.74.0"
> 127.0.0.1 - - [24/Nov/2024:07:19:01 +0000] "GET / HTTP/1.1" 200 3062 "-" "curl/7.74.0"
> ```
> 
> nginx的log也只记录到了我在容器内部成功的curl
> 
> 我估计不是talebook的问题，而是我的docker的问题，但我对docker掌握度不高，到处搜也没搞定，所以来请教一下



> [@XLXXLXXLX](https://github.com/XLXXLXXLX) 你其他通过frp穿透的服务可以正常使用吗？ 我理解是 你的frpc 和 talebook等服务运行在同一台设备上（或者同一个内网中），frps运行在有公网ip的服务器上。 在有公网ip的服务器上使用Nginx来反代frps的http端口，这样做是能跑通的。

请使用重写规则，例如：
````
location ~ ^/_nuxt/(.*)$ {
    rewrite ^/_nuxt/(.*)$ /your-subpath/_nuxt/$1 break;
    proxy_pass http://localhost:9000;
}
````
