### ISSUE TITLE
管理界面-用户管理进入奔溃

### ISSUE THREAD

**Issue by lgyjg** [talebook/talebook#76]
Exception:
Traceback (most recent call last):
  File "/var/www/calibre-webserver/webserver/handlers/base.py", line 54, in do
    try: rsp = func(self, *args, **kwargs)
  File "/var/www/calibre-webserver/webserver/handlers/base.py", line 74, in do
    return func(self, *args, **kwargs)
  File "/var/www/calibre-webserver/webserver/handlers/user.py", line 89, in get
    'provider': user.social_auth[0].provider if user.social_auth.count() else "register",
AttributeError: 'Reader' object has no attribute 'social_auth'

**Comment by lawipac** [comment]
A quick fix would be to comment this line. in **/var/www/calibre-web-server/webserver/handlers/users.py**

![Snag_44ab549](https://user-images.githubusercontent.com/10069433/132088768-e00e4913-7e55-4c4e-a0a0-ab7a219daa12.png)
