### ISSUE TITLE
点击用户管理报错（可以注册新用户但是无法对用户进行管理）

### ISSUE THREAD

**Issue by mayuyu1994** [talebook/talebook#88]
可以注册新用户但是无法对用户进行管理
报错信息如下：
Exception:
Traceback (most recent call last):
  File "/var/www/calibre-webserver/webserver/handlers/base.py", line 54, in do
    try: rsp = func(self, *args, **kwargs)
  File "/var/www/calibre-webserver/webserver/handlers/base.py", line 74, in do
    return func(self, *args, **kwargs)
  File "/var/www/calibre-webserver/webserver/handlers/user.py", line 89, in get
    'provider': user.social_auth[0].provider if user.social_auth.count() else "register",
AttributeError: 'Reader' object has no attribute 'social_auth'
<img width="1420" alt="WX20211004-222828@2x" src="https://user-images.githubusercontent.com/20795142/135869530-6efb7506-e480-48f7-90ea-0ff057c62705.png">

**Comment by mayuyu1994** [comment]
找到原因了就是这个，😓
![Uploading WX20211004-233726@2x.png…]()

**Comment by mayuyu1994** [comment]
找到原因了就是这个😓
<img width="1291" alt="WX20211004-233726@2x" src="https://user-images.githubusercontent.com/20795142/135881133-96e5b58a-f747-46fe-9d72-f943d810a8fa.png">
