### ISSUE TITLE
静读天下app读取opds还是有问题

### ISSUE THREAD

**Issue by gracehuahua** [talebook/talebook#94]
谢谢作者对前边问题的修复。试了一下，现在能打开了，但是opds有新的问题：貌似除了epub和pdf格式的电子书记录，其他的格式如mobi和azw3等都打不开，提示net::ERR_HTTP_RESPONSE_CODE_FAILURE。epub和pdf格式的打开正常。

**Comment by shentar** [comment]
我这里mobi和azw3都是直接弹出下载链接，下载后用也没问题。对于pdf和epub，实际上静读天下下载了两次。可能是app对于这两种格式有优化，其他格式未适配。

**Comment by shentar** [comment]
现在最新版本用起来是没问题的。

**Comment by muziling** [comment]
静读天下怎么配置，我输入的书库地址是 http://192.168.x.x:20080/opds，然后静读天下提示错误， 查看talebook.log，里面提示
[W 220512 13:16:02 web:2239] 404 GET /api/opds (172.17.0.1) 1.46ms

**Comment by shentar** [comment]
> 静读天下怎么配置，我输入的书库地址是 [http://192.168.x.x:20080/opds，然后静读天下提示错误，](http://192.168.x.x:20080/opds%EF%BC%8C%E7%84%B6%E5%90%8E%E9%9D%99%E8%AF%BB%E5%A4%A9%E4%B8%8B%E6%8F%90%E7%A4%BA%E9%94%99%E8%AF%AF%EF%BC%8C) 查看talebook.log，里面提示 [W 220512 13:16:02 web:2239] 404 GET /api/opds (172.17.0.1) 1.46ms

最后面要加个斜杠  http://192.168.x.x:20080/opds/

**Comment by xyx208** [comment]
> > 静读天下怎么配置，我输入的书库地址是 [http://192.168.x.x:20080/opds，然后静读天下提示错误，](http://192.168.x.x:20080/opds%EF%BC%8C%E7%84%B6%E5%90%8E%E9%9D%99%E8%AF%BB%E5%A4%A9%E4%B8%8B%E6%8F%90%E7%A4%BA%E9%94%99%E8%AF%AF%EF%BC%8C) 查看talebook.log，里面提示 [W 220512 13:16:02 web:2239] 404 GET /api/opds (172.17.0.1) 1.46ms
> 
> 最后面要加个斜杠 http://192.168.x.x:20080/opds/

`[E 221021 03:13:17 web:1789] Uncaught exception GET /opds/nav/4f6e6577657374 (61.166.141.249)
    HTTPServerRequest(protocol='http', host='www.xxx.cn', method='GET', uri='/opds/nav/4f6e6577657374', version='HTTP/1.0', remote_ip='xx.xx.xx.xx')
    Traceback (most recent call last):
      File "src/lxml/builder.py", line 175, in lxml.builder.ElementMaker.__init__.add_text
      File "src/lxml/etree.pyx", line 1161, in lxml.etree._Element.__getitem__
    IndexError: list index out of range
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/usr/local/lib/python3.9/dist-packages/tornado/web.py", line 1702, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/var/www/talebook/webserver/handlers/opds.py", line 741, in get
        self.write(self.opds_navcatalog(which, offset=offset))
      File "/var/www/talebook/webserver/handlers/opds.py", line 578, in opds_navcatalog
        return self.get_opds_all_books(which, page_url, up_url, offset=offset)
      File "/var/www/talebook/webserver/handlers/opds.py", line 498, in get_opds_all_books
        return self.get_opds_acquisition_feed(
      File "/var/www/talebook/webserver/handlers/opds.py", line 459, in get_opds_acquisition_feed
        AcquisitionFeed(
      File "/var/www/talebook/webserver/handlers/opds.py", line 399, in __init__
        self.root.append(ACQUISITION_ENTRY(item, db, updated, CFM, CKEYS, prefix))
      File "/var/www/talebook/webserver/handlers/opds.py", line 286, in ACQUISITION_ENTRY
        ans = E.entry(TITLE(title), E.author(E.name(authors)), ID(id_), UPDATED(updated))
      File "src/lxml/builder.py", line 228, in lxml.builder.ElementMaker.__call__
      File "src/lxml/builder.py", line 177, in lxml.builder.ElementMaker.__init__.add_text
      File "src/lxml/etree.pyx", line 1024, in lxml.etree._Element.text.__set__
      File "src/lxml/apihelpers.pxi", line 747, in lxml.etree._setNodeText
      File "src/lxml/apihelpers.pxi", line 735, in lxml.etree._createTextNode
      File "src/lxml/apihelpers.pxi", line 1540, in lxml.etree._utf8
    ValueError: All strings must be XML compatible: Unicode or ASCII, no NULL bytes or control characters`
   
大佬 ，这是什么问题呀？

**Comment by talebook** [comment]
> > > 静读天下怎么配置，我输入的书库地址是 [http://192.168.x.x:20080/opds，然后静读天下提示错误，](http://192.168.x.x:20080/opds%EF%BC%8C%E7%84%B6%E5%90%8E%E9%9D%99%E8%AF%BB%E5%A4%A9%E4%B8%8B%E6%8F%90%E7%A4%BA%E9%94%99%E8%AF%AF%EF%BC%8C) 查看talebook.log，里面提示 [W 220512 13:16:02 web:2239] 404 GET /api/opds (172.17.0.1) 1.46ms
> 
> > 
> 
> > 最后面要加个斜杠 http://192.168.x.x:20080/opds/
> 
> 
> 
> `[E 221021 03:13:17 web:1789] Uncaught exception GET /opds/nav/4f6e6577657374 (61.166.141.249)
> 
>     HTTPServerRequest(protocol='http', host='www.xxx.cn', method='GET', uri='/opds/nav/4f6e6577657374', version='HTTP/1.0', remote_ip='xx.xx.xx.xx')
> 
>     Traceback (most recent call last):
> 
>       File "src/lxml/builder.py", line 175, in lxml.builder.ElementMaker.__init__.add_text
> 
>       File "src/lxml/etree.pyx", line 1161, in lxml.etree._Element.__getitem__
> 
>     IndexError: list index out of range
> 
>     
> 
>     During handling of the above exception, another exception occurred:
> 
>     
> 
>     Traceback (most recent call last):
> 
>       File "/usr/local/lib/python3.9/dist-packages/tornado/web.py", line 1702, in _execute
> 
>         result = method(*self.path_args, **self.path_kwargs)
> 
>       File "/var/www/talebook/webserver/handlers/opds.py", line 741, in get
> 
>         self.write(self.opds_navcatalog(which, offset=offset))
> 
>       File "/var/www/talebook/webserver/handlers/opds.py", line 578, in opds_navcatalog
> 
>         return self.get_opds_all_books(which, page_url, up_url, offset=offset)
> 
>       File "/var/www/talebook/webserver/handlers/opds.py", line 498, in get_opds_all_books
> 
>         return self.get_opds_acquisition_feed(
> 
>       File "/var/www/talebook/webserver/handlers/opds.py", line 459, in get_opds_acquisition_feed
> 
>         AcquisitionFeed(
> 
>       File "/var/www/talebook/webserver/handlers/opds.py", line 399, in __init__
> 
>         self.root.append(ACQUISITION_ENTRY(item, db, updated, CFM, CKEYS, prefix))
> 
>       File "/var/www/talebook/webserver/handlers/opds.py", line 286, in ACQUISITION_ENTRY
> 
>         ans = E.entry(TITLE(title), E.author(E.name(authors)), ID(id_), UPDATED(updated))
> 
>       File "src/lxml/builder.py", line 228, in lxml.builder.ElementMaker.__call__
> 
>       File "src/lxml/builder.py", line 177, in lxml.builder.ElementMaker.__init__.add_text
> 
>       File "src/lxml/etree.pyx", line 1024, in lxml.etree._Element.text.__set__
> 
>       File "src/lxml/apihelpers.pxi", line 747, in lxml.etree._setNodeText
> 
>       File "src/lxml/apihelpers.pxi", line 735, in lxml.etree._createTextNode
> 
>       File "src/lxml/apihelpers.pxi", line 1540, in lxml.etree._utf8
> 
>     ValueError: All strings must be XML compatible: Unicode or ASCII, no NULL bytes or control characters`
> 
>    
> 
> 大佬 ，这是什么问题呀？
> 
> 

看报错是有不合法的字符。请提供下metadata.db文件

**Comment by lngg8er** [comment]
您好！我使用的是3.6.4版本，开启了私人模式。使用静读天下添加https://域名:端口号/opds/后，打开书库会直接显示以下内容：<?xml version='1.0' encoding='utf-8'?>
<feed xmlns="http://www.w3.org/2005/Atom" xmlns:dc="http://purl.org/dc/terms/" xmlns:opds="http://opds-spec.org/2010/catalog">
  <title>xxxBook Library</title>
  <subtitle>Books in your library</subtitle>
  <author>
    <name>xxxBook</name>
    <uri>http://calibre-ebook.com</uri>
  </author>
  <id>urn:calibre:main</id>
  <icon>/favicon.png</icon>
  <updated>2024-02-03T23:48:57+00:00</updated>
  <link type="application/atom+xml" rel="search" title="Search" href="/opds/search/{searchTerms}"/>
  <link type="application/atom+xml;type=feed;profile=opds-catalog" rel="start" href="/opds"/>
  <entry>
    <title>By Newest</title>
    <id>calibre-nav:d8fe553eb3716a016ce7e3b051e90bb8ff1d746f</id>
    <updated>2024-02-03T23:48:57+00:00</updated>
    <content type="text">Books sorted by Date</content>
    <link type="application/atom+xml;type=feed;profile=opds-catalog" href="/opds/nav/4f6e6577657374"/>
  </entry>
  <entry>
    <title>By Title</title>
    <id>calibre-nav:6996d1c1aaff7c7a3939e336db3b7b5db53fca00</id>
    <updated>2024-02-03T23:48:57+00:00</updated>
    <content type="text">Books sorted by Title</content>
    <link type="application/atom+xml;type=feed;profile=opds-catalog" href="/opds/nav/4f7469746c65"/>
  </entry>
  <entry>
    <title>By Authors</title>
    <id>calibre-nav:050c93c2a127e0e399dcfa556f3a931882ea6153</id>
    <updated>2024-02-03T23:48:57+00:00</updated>
    <content type="text">Books sorted by Authors</content>
    <link type="application/atom+xml;type=feed;profile=opds-catalog" href="/opds/nav/4e617574686f7273"/>
  </entry>
  <entry>
    <title>By Languages</title>
    <id>calibre-nav:0fcbe4dcce8c701c793d1329a6810684ccb135cc</id>
    <updated>2024-02-03T23:48:57+00:00</updated>
    <content type="text">Books sorted by Languages</content>
    <link type="application/atom+xml;type=feed;profile=opds-catalog" href="/opds/nav/4e6c616e677561676573"/>
  </entry>
  <entry>
    <title>By Publisher</title>
    <id>calibre-nav:b8fbd7fbe43c0be2dc86b7e61dc0520d39477689</id>
    <updated>2024-02-03T23:48:57+00:00</updated>
    <content type="text">Books sorted by Publisher</content>
    <link type="application/atom+xml;type=feed;profile=opds-catalog" href="/opds/nav/4e7075626c6973686572"/>
  </entry>
  <entry>
    <title>By Rating</title>
    <id>calibre-nav:85e6c45eea3bb60c94461299c120d02ba129f0d8</id>
    <updated>2024-02-03T23:48:57+00:00</updated>
    <content type="text">Books sorted by Rating</content>
    <link type="application/atom+xml;type=feed;profile=opds-catalog" href="/opds/nav/4e726174696e67"/>
  </entry>
  <entry>
    <title>By Series</title>
    <id>calibre-nav:4742db4523b9c6f201c3177307bcee92ee7060a9</id>
    <updated>2024-02-03T23:48:57+00:00</updated>
    <content type="text">Books sorted by Series</content>
    <link type="application/atom+xml;type=feed;profile=opds-catalog" href="/opds/nav/4e736572696573"/>
  </entry>
  <entry>
    <title>By Tags</title>
    <id>calibre-nav:0b31ff0412bc3c1957dac97d9acd5328de094bcc</id>
    <updated>2024-02-03T23:48:57+00:00</updated>
    <content type="text">Books sorted by Tags</content>
    <link type="application/atom+xml;type=feed;profile=opds-catalog" href="/opds/nav/4e74616773"/>
  </entry>
</feed>

**Comment by wyatsun** [comment]
用静读天下连接NAS外网opds链接（https://xxx.xxx.xxx:1688/opds/），提示报错如图

<img width="1080" height="2400" alt="Image" src="https://github.com/user-attachments/assets/3925e5f9-5f74-4665-a454-ac565ea9ea85" />
